var GourceModule=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;var h=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;h.expectedDataFileDownloads||(h.expectedDataFileDownloads=0);h.expectedDataFileDownloads++;
(()=>{var a="undefined"!=typeof ENVIRONMENT_IS_WASM_WORKER&&ENVIRONMENT_IS_WASM_WORKER;if(!("undefined"!=typeof ENVIRONMENT_IS_PTHREAD&&ENVIRONMENT_IS_PTHREAD||a)){var b=globalThis.process&&globalThis.process.versions&&globalThis.process.versions.node&&"renderer"!=globalThis.process.type;(async function(c){async function d(n,q){if(b){var r=require("fs").readFileSync(n);return(new Uint8Array(r)).buffer}h.dataFileDownloads||(h.dataFileDownloads={});try{var v=await fetch(n)}catch(M){throw Error(`Network Error: ${n}`,
{e:M});}if(!v.ok)throw Error(`${v.status}: ${v.url}`);r=[];q=Number(v.headers.get("Content-Length")||q);let D=0;h.setStatus&&h.setStatus("Downloading data...");for(v=v.body.getReader();;){var {done:N,value:O}=await v.read();if(N)break;r.push(O);D+=O.length;h.dataFileDownloads[n]={loaded:D,total:q};let M=0,T=0;for(var R of Object.values(h.dataFileDownloads))M+=R.loaded,T+=R.total;h.setStatus&&h.setStatus(`Downloading data... (${M}/${T})`)}n=new Uint8Array(r.map(M=>M.length).reduce((M,T)=>M+T,0));R=
0;for(const M of r)n.set(M,R),R+=M.length;return n.buffer}async function e(n){n.FS_createPath("/","data",!0,!0);n.FS_createPath("/data","fonts",!0,!0);n.FS_createPath("/data","shaders",!0,!0);for(var q of c.files)n.addRunDependency(`fp ${q.filename}`);n.addRunDependency("datafile_build/wasm/wasm32/release/gource-web.data");n.preloadResults||(n.preloadResults={});n.preloadResults["build/wasm/wasm32/release/gource-web.data"]={Kk:!1};m||=await k;(async function(r){if(!r)throw Error("Loading data file failed.");
if(r.constructor.name!==ArrayBuffer.name)throw Error("bad input to processPackageData "+r.constructor.name);r=new Uint8Array(r);for(var v of c.files){var D=v.filename;n.FS_createDataFile(D,null,r.subarray(v.start,v.end),!0,!0,!0);n.removeRunDependency(`fp ${D}`)}n.removeRunDependency("datafile_build/wasm/wasm32/release/gource-web.data")})(m)}"object"===typeof window?window.encodeURIComponent(window.location.pathname.substring(0,window.location.pathname.lastIndexOf("/"))+"/"):"undefined"===typeof process&&
"undefined"!==typeof location&&encodeURIComponent(location.pathname.substring(0,location.pathname.lastIndexOf("/"))+"/");var f=h.locateFile?h.locateFile("gource-web.data",""):"gource-web.data",g=c.remote_package_size,k,m=h.getPreloadedPackage&&h.getPreloadedPackage(f,g);m||(k=d(f,g));h.calledRun?e(h):(h.preRun||(h.preRun=[]),h.preRun.push(e))})({files:[{filename:"/data/beam.png",start:0,end:367},{filename:"/data/bloom.png",start:367,end:13184},{filename:"/data/bloom.tga",start:13184,end:184899},{filename:"/data/bloom_alpha.png",
start:184899,end:199926},{filename:"/data/bloom_alpha.tga",start:199926,end:417350},{filename:"/data/file.png",start:417350,end:461533},{filename:"/data/fonts/FreeSans.ttf",start:461533,end:1175989},{filename:"/data/fonts/README",start:1175989,end:1180302},{filename:"/data/gource.1",start:1180302,end:1193972},{filename:"/data/gource.style",start:1193972,end:1194265},{filename:"/data/shaders/basic.frag",start:1194265,end:1194573},{filename:"/data/shaders/basic.vert",start:1194573,end:1194912},{filename:"/data/shaders/bloom.frag",
start:1194912,end:1195449},{filename:"/data/shaders/bloom.vert",start:1195449,end:1195886},{filename:"/data/shaders/shadow.frag",start:1195886,end:1196193},{filename:"/data/shaders/shadow.vert",start:1196193,end:1196532},{filename:"/data/shaders/text.frag",start:1196532,end:1197394},{filename:"/data/shaders/text.vert",start:1197394,end:1197733},{filename:"/data/user.png",start:1197733,end:1260407}],remote_package_size:1260407})}})();var da=[],ea="./this.program",fa=(a,b)=>{throw b;};
"undefined"!=typeof __filename?_scriptName=__filename:ba&&(_scriptName=self.location.href);var ha="",ia,ja;
if(ca){var fs=require("fs");ha=__dirname+"/";ja=a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ha=(new URL(".",_scriptName)).href}catch{}ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ia=async a=>
{if(ka(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var la=console.log.bind(console),l=console.error.bind(console),ma,na=!1,oa,ka=a=>a.startsWith("file://"),pa,qa,p,t,ra,sa,u,w,x,ta,ua,va=!1;
function wa(){var a=xa.buffer;p=new Int8Array(a);ra=new Int16Array(a);t=new Uint8Array(a);sa=new Uint16Array(a);u=new Int32Array(a);w=new Uint32Array(a);x=new Float32Array(a);ta=new Float64Array(a);ua=new BigInt64Array(a);new BigUint64Array(a)}function ya(a){h.onAbort?.(a);a="Aborted("+a+")";l(a);na=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");qa?.(a);throw a;}var za;
async function Aa(a){if(!ma)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==za&&ma)a=new Uint8Array(ma);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}async function Ba(a,b){try{var c=await Aa(a);return await WebAssembly.instantiate(c,b)}catch(d){l(`failed to asynchronously prepare wasm: ${d}`),ya(d)}}
async function Ca(a){var b=za;if(!ma&&!ka(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){l(`wasm streaming compile failed: ${d}`),l("falling back to ArrayBuffer instantiation")}return Ba(b,a)}class Da{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ea=a=>{for(;0<a.length;)a.shift()(h)},Fa=[],Ga=[],Ha=()=>{var a=h.preRun.shift();Ga.push(a)},Ia=!0,Ja=[],y=a=>{var b=Ja[a];b||(Ja[a]=b=Ka.get(a));return b},La=[],Ma=0,Na=0;class Oa{constructor(a){this.Gj=a;this.ii=a-24}}
var Ra=a=>{var b=Na;if(!b)return Pa(0),0;var c=new Oa(b);w[c.ii+16>>2]=b;var d=w[c.ii+4>>2];if(!d)return Pa(0),b;for(var e of a){if(0===e||e===d)break;if(Qa(e,d,c.ii+16))return Pa(e),b}Pa(d);return b},Sa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ta=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Sa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");
return(b?"/":"")+a},Ua=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Va=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Wa=()=>{if(ca){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Xa=a=>{(Xa=Wa())(a)},Za=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:Ya;if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");
if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Sa(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},$a=globalThis.TextDecoder&&new TextDecoder,z=(a,b=0,c,d)=>{var e=b;c=e+c;if(d)d=c;else{for(;a[e]&&!(e>=c);)++e;d=e}if(16<d-b&&a.buffer&&$a)return $a.decode(a.subarray(b,d));for(e="";b<d;)if(c=a[b++],c&128){var f=a[b++]&63;if(192==(c&224))e+=String.fromCharCode((c&31)<<6|f);else{var g=a[b++]&63;c=224==(c&240)?(c&15)<<12|f<<6|g:(c&7)<<18|f<<12|g<<6|a[b++]&63;65536>c?e+=String.fromCharCode(c):
(c-=65536,e+=String.fromCharCode(55296|c>>10,56320|c&1023))}}else e+=String.fromCharCode(c);return e},ab=[],bb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},A=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>
6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},cb=a=>{var b=Array(bb(a)+1);a=A(a,b,0,b.length);b.length=a;return b},db=[];function eb(a,b){db[a]={input:[],output:[],Di:b};fb(a,gb)}
var gb={open(a){var b=db[a.node.rdev];if(!b)throw new B(43);a.tty=b;a.seekable=!1},close(a){a.tty.Di.fsync(a.tty)},fsync(a){a.tty.Di.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Di.Ij)throw new B(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Di.Ij(a.tty)}catch(k){throw new B(29);}if(void 0===g&&0===e)throw new B(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Di.tj)throw new B(60);try{for(var e=0;e<d;e++)a.tty.Di.tj(a.tty,b[c+e])}catch(f){throw new B(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},hb={Ij(){a:{if(!ab.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}ab=cb(a)}a=ab.shift()}return a},tj(a,b){null===b||10===b?(la(z(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&
(la(z(a.output)),a.output=[])},ik(){return{zk:25856,Bk:5,yk:191,Ak:35387,xk:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},jk(){return 0},kk(){return[24,80]}},ib={tj(a,b){null===b||10===b?(l(z(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(l(z(a.output)),a.output=[])}},kb=a=>{a=65536*Math.ceil(a/65536);var b=jb(65536,a);b&&t.fill(0,b,b+a);return b},C={zi:null,Ci(){return C.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&
61440)||4096===(c&61440))throw new B(63);C.zi||(C.zi={dir:{node:{ui:C.ei.ui,Ai:C.ei.Ai,lookup:C.ei.lookup,cj:C.ei.cj,rename:C.ei.rename,unlink:C.ei.unlink,rmdir:C.ei.rmdir,readdir:C.ei.readdir,symlink:C.ei.symlink},stream:{yi:C.fi.yi}},file:{node:{ui:C.ei.ui,Ai:C.ei.Ai},stream:{yi:C.fi.yi,read:C.fi.read,write:C.fi.write,Vi:C.fi.Vi,ej:C.fi.ej}},link:{node:{ui:C.ei.ui,Ai:C.ei.Ai,readlink:C.ei.readlink},stream:{}},Ej:{node:{ui:C.ei.ui,Ai:C.ei.Ai},stream:lb}});c=mb(a,b,c,d);E(c.mode)?(c.ei=C.zi.dir.node,
c.fi=C.zi.dir.stream,c.gi={}):32768===(c.mode&61440)?(c.ei=C.zi.file.node,c.fi=C.zi.file.stream,c.ji=0,c.gi=null):40960===(c.mode&61440)?(c.ei=C.zi.link.node,c.fi=C.zi.link.stream):8192===(c.mode&61440)&&(c.ei=C.zi.Ej.node,c.fi=C.zi.Ej.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.gi[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},Mk(a){return a.gi?a.gi.subarray?a.gi.subarray(0,a.ji):new Uint8Array(a.gi):new Uint8Array(0)},ei:{ui(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=
a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;E(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.ji:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},Ai(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.ji!=b&&(0==b?(a.gi=null,a.ji=0):(c=a.gi,a.gi=new Uint8Array(b),c&&a.gi.set(c.subarray(0,Math.min(b,
a.ji))),a.ji=b)))},lookup(){C.hj||(C.hj=new B(44),C.hj.stack="<generic error, no stack>");throw C.hj;},cj(a,b,c,d){return C.createNode(a,b,c,d)},rename(a,b,c){try{var d=nb(b,c)}catch(f){}if(d){if(E(a.mode))for(var e in d.gi)throw new B(55);ob(d)}delete a.parent.gi[a.name];b.gi[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.gi[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=nb(a,b),d;for(d in c.gi)throw new B(55);delete a.gi[b];a.ctime=a.mtime=Date.now()},
readdir(a){return[".","..",...Object.keys(a.gi)]},symlink(a,b,c){a=C.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new B(28);return a.link}},fi:{read(a,b,c,d,e){var f=a.node.gi;if(e>=a.node.ji)return 0;a=Math.min(a.node.ji-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===p.buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.gi||a.gi.subarray)){if(f)return a.gi=
b.subarray(c,c+d),a.ji=d;if(0===a.ji&&0===e)return a.gi=b.slice(c,c+d),a.ji=d;if(e+d<=a.ji)return a.gi.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.gi?a.gi.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.gi,a.gi=new Uint8Array(f),0<a.ji&&a.gi.set(g.subarray(0,a.ji),0));if(a.gi.subarray&&b.subarray)a.gi.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.gi[e+f]=b[c+f];a.ji=Math.max(a.ji,e+d);return d},yi(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&
(b+=a.node.ji);if(0>b)throw new B(28);return b},Vi(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new B(43);a=a.node.gi;if(e&2||!a||a.buffer!==p.buffer){d=!0;e=kb(b);if(!e)throw new B(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);p.set(a,e)}}else d=!1,e=a.byteOffset;return{ii:e,Cj:d}},ej(a,b,c,d){C.fi.write(a,b,0,d,c,!1);return 0}}},pb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},qb=async a=>{a=await ia(a);return new Uint8Array(a)},rb=0,
sb=null,tb=()=>{rb--;h.monitorRunDependencies?.(rb);if(0==rb&&sb){var a=sb;sb=null;a()}},ub=()=>{rb++;h.monitorRunDependencies?.(rb)},vb=[],yb=async(a,b)=>{"undefined"!=typeof wb&&xb();for(var c of vb)if(c.canHandle(b))return c.handle(a,b);return a},zb=null,Ab={},Bb=[],Cb=1,Db=null,Ya="/",Eb=!1,Fb=!0,Gb={},B=class{name="ErrnoError";constructor(a){this.hi=a}},Hb=class{ni={};node=null;get flags(){return this.ni.flags}set flags(a){this.ni.flags=a}get position(){return this.ni.position}set position(a){this.ni.position=
a}},Ib=class{ei={};fi={};Pi=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Ci=a.Ci;this.id=Cb++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get mk(){return E(this.mode)}get lk(){return 8192===(this.mode&61440)}};
function Jb(a,b={}){if(!a)throw new B(44);b.kj??(b.kj=!0);"/"===a.charAt(0)||(a=Ya+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=zb,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Ua(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Ta(e+"/"+a[f]);try{d=nb(d,a[f])}catch(k){if(44===k?.hi&&g&&b.qk)return{path:e};throw k;}!d.Pi||g&&!b.kj||(d=d.Pi.root);if(40960===(d.mode&61440)&&(!g||b.Oi)){if(!d.ei.readlink)throw new B(52);
d=d.ei.readlink(d);"/"===d.charAt(0)||(d=Ua(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new B(32);}function Kb(a){for(var b;;){if(a===a.parent)return a=a.Ci.Pj,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Lb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Db.length}
function ob(a){var b=Lb(a.parent.id,a.name);if(Db[b]===a)Db[b]=a.Qi;else for(b=Db[b];b;){if(b.Qi===a){b.Qi=a.Qi;break}b=b.Qi}}function nb(a,b){var c=E(a.mode)?(c=Mb(a,"x"))?c:a.ei.lookup?0:2:54;if(c)throw new B(c);for(c=Db[Lb(a.id,b)];c;c=c.Qi){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ei.lookup(a,b)}function mb(a,b,c,d){a=new Ib(a,b,c,d);b=Lb(a.parent.id,a.name);a.Qi=Db[b];return Db[b]=a}function E(a){return 16384===(a&61440)}
function Nb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Mb(a,b){if(Fb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ob(a,b){if(!E(a.mode))return 54;try{return nb(a,b),20}catch(c){}return Mb(a,"wx")}
function Pb(a,b,c){try{var d=nb(a,b)}catch(e){return e.hi}if(a=Mb(a,"wx"))return a;if(c){if(!E(d.mode))return 54;if(d===d.parent||Kb(d)===Ya)return 10}else if(E(d.mode))return 31;return 0}function Qb(a,b){if(!a)throw new B(b);return a}function Rb(a){a=Bb[a];if(!a)throw new B(8);return a}function Sb(a,b=-1){a=Object.assign(new Hb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!Bb[b])break a;throw new B(33);}a.fd=b;return Bb[b]=a}function Tb(a,b=-1){a=Sb(a,b);a.fi?.Ik?.(a);return a}
function Ub(a,b){var c=null?.fi.Ai,d=c?null:a;c??=a.ei.Ai;Qb(c,63);c(d,b)}var lb={open(a){a.fi=Ab[a.node.rdev].fi;a.fi.open?.(a)},yi(){throw new B(70);}};function fb(a,b){Ab[a]={fi:b}}function Vb(a,b){var c="/"===b;if(c&&zb)throw new B(10);if(!c&&b){var d=Jb(b,{kj:!1});b=d.path;d=d.node;if(d.Pi)throw new B(10);if(!E(d.mode))throw new B(54);}b={type:a,Sk:{},Pj:b,pk:[]};a=a.Ci(b);a.Ci=b;b.root=a;c?zb=a:d&&(d.Pi=b,d.Ci&&d.Ci.pk.push(b))}
function Wb(a,b,c){var d=Jb(a,{parent:!0}).node;a=Va(a);if(!a)throw new B(28);if("."===a||".."===a)throw new B(20);var e=Ob(d,a);if(e)throw new B(e);if(!d.ei.cj)throw new B(63);return d.ei.cj(d,a,b,c)}function Xb(a,b=438){return Wb(a,b&4095|32768,0)}function Yb(a){return Wb(a,16895,0)}function Zb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Wb(a,b|8192,c)}
function $b(a,b){if(!Za(a))throw new B(44);var c=Jb(b,{parent:!0}).node;if(!c)throw new B(44);b=Va(b);var d=Ob(c,b);if(d)throw new B(d);if(!c.ei.symlink)throw new B(63);c.ei.symlink(c,b,a)}function ac(a){var b=Jb(a,{parent:!0}).node;a=Va(a);var c=nb(b,a),d=Pb(b,a,!0);if(d)throw new B(d);if(!b.ei.rmdir)throw new B(63);if(c.Pi)throw new B(10);b.ei.rmdir(b,a);ob(c)}
function bc(a){var b=Jb(a,{parent:!0}).node;if(!b)throw new B(44);a=Va(a);var c=nb(b,a),d=Pb(b,a,!1);if(d)throw new B(d);if(!b.ei.unlink)throw new B(63);if(c.Pi)throw new B(10);b.ei.unlink(b,a);ob(c)}function cc(a,b){a=Jb(a,{Oi:!b}).node;return Qb(a.ei.ui,63)(a)}function dc(a,b){a="string"==typeof a?Jb(a,{Oi:!0}).node:a;Ub(a,{mode:b&4095|a.mode&-4096,ctime:Date.now(),Hk:void 0})}
function ec(a,b,c=438){if(""===a)throw new B(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=Jb(a,{Oi:!(b&131072),qk:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new B(20);}else{if(e)throw new B(31);d=Wb(a,c|511,0);f=!0}if(!d)throw new B(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!E(d.mode))throw new B(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:E(d.mode)&&("r"!==Nb(b)||b&576)?31:Mb(d,Nb(b)):44))throw new B(e);if(b&512&&!f){e=d;e="string"==typeof e?Jb(e,{Oi:!0}).node:e;if(E(e.mode))throw new B(31);if(32768!==(e.mode&61440))throw new B(28);var g=Mb(e,"w");if(g)throw new B(g);Ub(e,{size:0,timestamp:Date.now()})}b&=-131713;e=Sb({node:d,path:Kb(d),flags:b,seekable:!0,position:0,fi:d.fi,tk:[],error:!1});e.fi.open&&e.fi.open(e);f&&dc(d,c&511);!h.logReadFiles||b&1||a in Gb||(Gb[a]=1);return e}
function fc(a){if(null===a.fd)throw new B(8);a.Ii&&(a.Ii=null);try{a.fi.close&&a.fi.close(a)}catch(b){throw b;}finally{Bb[a.fd]=null}a.fd=null}function gc(a,b,c){if(null===a.fd)throw new B(8);if(!a.seekable||!a.fi.yi)throw new B(70);if(0!=c&&1!=c&&2!=c)throw new B(28);a.position=a.fi.yi(a,b,c);a.tk=[];return a.position}
function hc(a,b,c,d,e,f){if(0>d||0>e)throw new B(28);if(null===a.fd)throw new B(8);if(0===(a.flags&2097155))throw new B(8);if(E(a.node.mode))throw new B(31);if(!a.fi.write)throw new B(28);a.seekable&&a.flags&1024&&gc(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new B(70);b=a.fi.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function ic(a,b){a="string"==typeof a?a:Kb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ta(a+"/"+c);try{Yb(d)}catch(e){if(20!=e.hi)throw e;}a=d}}return d}function kc(a,b,c,d){a=Ta(("string"==typeof a?a:Kb(a))+"/"+b);return Xb(a,pb(c,d))}
function lc(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:Kb(a),g=b?Ta(a+"/"+b):a);a=pb(d,e);g=Xb(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}dc(g,a|146);b=ec(g,577);hc(b,c,0,c.length,0,f);fc(b);dc(g,a)}}
function mc(a,b,c,d){a=Ta(("string"==typeof a?a:Kb(a))+"/"+b);b=pb(!!c,!!d);mc.Nj??(mc.Nj=64);var e=mc.Nj++<<8|0;fb(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,k,m){for(var n=0,q=0;q<m;q++){try{var r=c()}catch(v){throw new B(29);}if(void 0===r&&0===n)throw new B(6);if(null===r||void 0===r)break;n++;g[k+q]=r}n&&(f.node.atime=Date.now());return n},write(f,g,k,m){for(var n=0;n<m;n++)try{d(g[k+n])}catch(q){throw new B(29);}m&&(f.node.mtime=f.node.ctime=Date.now());return n}});
return Zb(a,b,e)}function nc(a){if(!(a.lk||a.mk||a.link||a.gi))if(globalThis.XMLHttpRequest)ya("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.gi=ja(a.url)}catch(b){throw new B(29);}}
function oc(a,b,c,d,e){function f(q,r,v,D,N){q=q.node.gi;if(N>=q.length)return 0;D=Math.min(q.length-N,D);if(q.slice)for(var O=0;O<D;O++)r[v+O]=q[N+O];else for(O=0;O<D;O++)r[v+O]=q.get(N+O);return D}class g{nj=!1;ni=[];ij=void 0;Kj=0;Jj=0;get(q){if(!(q>this.length-1||0>q)){var r=q%this.chunkSize;return this.ij(q/this.chunkSize|0)[r]}}nk(q){this.ij=q}Mj(){var q=new XMLHttpRequest;q.open("HEAD",c,!1);q.send(null);200<=q.status&&300>q.status||304===q.status||ya("Couldn't load "+c+". Status: "+q.status);
var r=Number(q.getResponseHeader("Content-length")),v,D=(v=q.getResponseHeader("Accept-Ranges"))&&"bytes"===v;q=(v=q.getResponseHeader("Content-Encoding"))&&"gzip"===v;var N=1048576;D||(N=r);var O=this;O.nk(R=>{var M=R*N,T=(R+1)*N-1;T=Math.min(T,r-1);if("undefined"==typeof O.ni[R]){var jc=O.ni;M>T&&ya("invalid range ("+M+", "+T+") or no bytes requested!");T>r-1&&ya("only "+r+" bytes available! programmer error!");var W=new XMLHttpRequest;W.open("GET",c,!1);r!==N&&W.setRequestHeader("Range","bytes="+
M+"-"+T);W.responseType="arraybuffer";W.overrideMimeType&&W.overrideMimeType("text/plain; charset=x-user-defined");W.send(null);200<=W.status&&300>W.status||304===W.status||ya("Couldn't load "+c+". Status: "+W.status);M=void 0!==W.response?new Uint8Array(W.response||[]):cb(W.responseText||"");jc[R]=M}"undefined"==typeof O.ni[R]&&ya("doXHR failed!");return O.ni[R]});if(q||!r)N=r=1,N=r=this.ij(0).length,la("LazyFiles on gzip forces download of the whole file when length is accessed");this.Kj=r;this.Jj=
N;this.nj=!0}get length(){this.nj||this.Mj();return this.Kj}get chunkSize(){this.nj||this.Mj();return this.Jj}}if(globalThis.XMLHttpRequest){ba||ya("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");var k=new g;var m=void 0}else m=c,k=void 0;var n=kc(a,b,d,e);k?n.gi=k:m&&(n.gi=null,n.url=m);Object.defineProperties(n,{ji:{get:function(){return this.gi.length}}});a={};for(const [q,r]of Object.entries(n.fi))a[q]=(...v)=>{nc(n);return r(...v)};
a.read=(q,r,v,D,N)=>{nc(n);return f(q,r,v,D,N)};a.Vi=(q,r,v)=>{nc(n);var D=kb(r);if(!D)throw new B(48);f(q,p,D,r,v);return{ii:D,Cj:!0}};n.fi=a;return n}var F={},pc=(a,b,c)=>a?z(t,a,b,c):"";function qc(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?Ya:Rb(a).path;if(0==b.length){if(!c)throw new B(44);return a}return a+"/"+b}
function rc(a,b){w[a>>2]=b.dev;w[a+4>>2]=b.mode;w[a+8>>2]=b.nlink;w[a+12>>2]=b.uid;w[a+16>>2]=b.gid;w[a+20>>2]=b.rdev;ua[a+24>>3]=BigInt(b.size);u[a+32>>2]=4096;u[a+36>>2]=b.blocks;var c=b.atime.getTime(),d=b.mtime.getTime(),e=b.ctime.getTime();ua[a+40>>3]=BigInt(Math.floor(c/1E3));w[a+48>>2]=c%1E3*1E6;ua[a+56>>3]=BigInt(Math.floor(d/1E3));w[a+64>>2]=d%1E3*1E6;ua[a+72>>3]=BigInt(Math.floor(e/1E3));w[a+80>>2]=e%1E3*1E6;ua[a+88>>3]=BigInt(b.ino);return 0}
var sc=void 0,tc=()=>{var a=u[+sc>>2];sc+=4;return a},uc=0,vc=a=>0===a%4&&(0!==a%100||0===a%400),wc=[0,31,60,91,121,152,182,213,244,274,305,335],xc=[0,31,59,90,120,151,181,212,243,273,304,334],yc={},zc=a=>{a instanceof Da||"unwind"==a||fa(1,a)},Ac=a=>{oa=a;Ia||0<uc||(h.onExit?.(a),na=!0);fa(a,new Da(a))},Bc=()=>{if(!(Ia||0<uc))try{var a=oa;oa=a;Ac(a)}catch(b){zc(b)}},Cc=a=>{if(!na)try{a(),Bc()}catch(b){zc(b)}};
function Dc(){return document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement}var Ec=a=>{setTimeout(()=>{Cc(a)},1E4)},Fc=!1,Gc=[],Hc={};
function xb(){function a(){Fc=document.pointerLockElement===h.canvas}if(!Ic){Ic=!0;vb.push({canHandle:function(c){return!h.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c)},handle:async function(c,d){var e=new Blob([c],{type:Jc(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:Jc(d)}));var f=URL.createObjectURL(e);return new Promise((g,k)=>{var m=new Image;m.onload=()=>{var n=document.createElement("canvas");n.width=m.width;n.height=m.height;n.getContext("2d").drawImage(m,
0,0);Hc[d]=n;URL.revokeObjectURL(f);g(c)};m.onerror=()=>{l(`Image ${f} could not be decoded`);k()};m.src=f})}});vb.push({canHandle:function(c){return!h.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:async function(c,d){return new Promise(e=>{function f(){g||(g=!0,e(c))}var g=!1,k=new Blob([c],{type:Jc(d)});k=URL.createObjectURL(k);var m=new Audio;m.addEventListener("canplaythrough",()=>f(m),!1);m.onerror=function(){if(!g){l(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var n="data:audio/x-"+d.slice(-3)+";base64,",q="",r=0,v=0,D=0;D<c.length;D++)for(r=r<<8|c[D],v+=8;6<=v;){var N=r>>v-6&63;v-=6;q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[N]}2==v?(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(r&3)<<4],q+="=="):4==v&&(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(r&15)<<2],q+="=");m.src=n+q;f(m)}};m.src=k;Ec(()=>{f(m)})})}});var b=h.canvas;b&&(document.addEventListener("pointerlockchange",
a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!Fc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}function Kc(a,b,c,d){if(b&&h.ctx&&a==h.canvas)return h.ctx;var e;if(b){var f={antialias:!1,alpha:!1,Oj:2};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof Lc&&(e=Mc(a,f)))var k=Nc[e].wi}else k=a.getContext("2d");if(!k)return null;c&&(h.ctx=k,b&&Oc(e),Gc.forEach(m=>m()),xb());return k}
function Jc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}
var wb={},Ic,G=12288,Pc=!1,Qc=0,Rc=0,Sc=0,H={alpha:!1,depth:!1,stencil:!1,antialias:!1},Tc={},Uc,I,Vc=a=>{var b="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");return(a.getSupportedExtensions()||
[]).filter(c=>b.includes(c))},Wc=1,Xc=[],Yc={},J=[],Zc=[],$c=[],ad=[],K=[],bd=[],Nc=[],L=[],cd=[],dd=[],ed=[],fd=[1,1,2,2,4,4,4,2,3,4,8],gd={},hd={},jd=4,kd=0,ld=a=>{for(var b=Wc++,c=a.length;c<b;c++)a[c]=null;for(;a[b];)b=Wc++;return b},md=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=I[c](),g=f&&ld(d);f?(f.name=g,d[g]=f):P||=1282;u[b+4*e>>2]=g}},nd=a=>{a=32-Math.clz32(0===a?0:a-1);var b=Q.Si[a];if(b)return b;b=I.getParameter(34965);Q.Si[a]=I.createBuffer();I.bindBuffer(34963,Q.Si[a]);I.bufferData(34963,
1<<a,35048);I.bindBuffer(34963,b);return Q.Si[a]},pd=a=>{od=!1;for(var b=0;b<Q.qj;++b){var c=Q.Bi[b];if(c.Mi&&c.enabled){od=!0;var d=c.size;var e=c.type,f=c.stride;d=0<f?a*f:d*fd[e-5120]*a;e=32-Math.clz32(0===d?0:d-1);f=Q.Ti[e];var g=Q.Gi[e];Q.Gi[e]=Q.Gi[e]+1&63;var k=f[g];k?e=k:(k=I.getParameter(34964),f[g]=I.createBuffer(),I.bindBuffer(34962,f[g]),I.bufferData(34962,1<<e,35048),I.bindBuffer(34962,k),e=f[g]);I.bindBuffer(34962,e);I.bufferSubData(34962,0,t.subarray(c.ii,c.ii+d));c.yj.call(I,b,c.size,
c.type,c.rj,c.stride,0)}}},Mc=(a,b)=>{a.ni||(a.ni=a.getContext,a.getContext=function(d,e){e=a.ni(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?qd(c,b):0},qd=(a,b)=>{var c=ld(Nc),d={handle:c,attributes:b,version:b.Oj,wi:a};a.canvas&&(a.canvas.Hi=d);Nc[c]=d;if("undefined"==typeof b.ck||b.ck)if((a=d)||(a=Q),!a.gk){a.gk=!0;b=a.wi;b.Rk=b.getExtension("WEBGL_multi_draw");b.ek=b.getExtension("EXT_polygon_offset_clamp");b.dk=b.getExtension("EXT_clip_control");
b.uk=b.getExtension("WEBGL_polygon_mode");b.Gk=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Pk=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.ti=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.ti)b.ti=b.getExtension("EXT_disjoint_timer_query");for(var e of Vc(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}d.qj=d.wi.getParameter(34921);d.Bi=[];for(e=0;e<d.qj;e++)d.Bi[e]={enabled:!1,Mi:!1,size:0,
type:0,rj:0,stride:0,ii:0,yj:null};d.Gi=[];d.fj=[];d.Gi.length=d.fj.length=22;d.Ti=[];d.Wi=[];d.Ti.length=d.Wi.length=22;d.Si=[];d.Si.length=22;for(e=0;21>=e;++e){d.Si[e]=null;d.Gi[e]=d.fj[e]=0;d.Ti[e]=[];d.Wi[e]=[];a=d.Ti[e];b=d.Wi[e];a.length=b.length=64;for(var f=0;64>f;++f)a[f]=b[f]=null}return c},Oc=a=>{Q=Nc[a];h.ctx=I=Q?.wi},Lc={},P,Q,od,sd=a=>{var b=bb(a)+1,c=rd(b);c&&A(a,t,c,b);return c},Jd=(a,b,c,d,e)=>{function f(){return g<td?(Bc(),!1):!0}ud=a;vd=d;var g=td;wd=!1;xd=function(){if(!na)if(0<
yd.length){var k=yd.shift();k.Lk(k.vk);if(zd){var m=zd,n=0==m%1?m-1:Math.floor(m);zd=k.Dk?n:(8*m+(n+.5))/9}h.setStatus&&(k=h.statusMessage||"Please wait...",m=zd??0,n=Ad.Jk??0,m?m<n?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(k):h.setStatus(""));f()&&setTimeout(xd,0)}else if(f())if(Bd=Bd+1|0,1==Cd&&1<Dd&&0!=Bd%Dd)Ed();else{0==Cd&&(Fd=performance.now());a:if(!na){for(k of Gd)if(!1===k())break a;Cc(a);for(m of Hd)m()}f()&&Ed()}};e||(0<b?Id(0,1E3/b):Id(1,1),Ed());if(c)throw"unwind";
},wd=!1,Ed=null,td=0,ud=null,vd=0,Cd=0,Dd=0,Bd=0,yd=[],Gd=[],Hd=[];function Kd(){Ed=null;td++}var Ld=0;function Md(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Ld)Ld=b+1E3/60;else for(;b+2>=Ld;)Ld+=1E3/60;setTimeout(a,Math.max(Ld-b,0))}}
var Ad={},xd,zd,Fd,Nd,Id=(a,b)=>{Cd=a;Dd=b;if(ud)if(wd||=!0,0==a)Ed=function(){setTimeout(xd,Math.max(0,Fd+b-performance.now())|0)};else if(1==a)Ed=function(){Md(xd)};else if(2==a){if(!Nd)if(globalThis.setImmediate)Nd=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Nd=d=>{c.push(d);ba?(h.setImmediates??(h.setImmediates=[]),h.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}Ed=function(){Nd(xd)}}},Od=[],Pd=(a,b)=>{Od.length=0;for(var c;c=t[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Od.push(112==c?w[b>>2]:106==c?ua[b>>3]:105==c?u[b>>2]:ta[b>>3]);b+=d?8:4}return Od};function Qd(a){var b=S.mi[a];b.target.removeEventListener(b.ki,b.Fj,b.pi);S.mi.splice(a,1)}
function Rd(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var k in f)if(f[k]!=g[k])return!1;return!0}for(var e of S.Ei)if(e.uj==a&&d(e.Dj,c))return;S.Ei.push({uj:a,Rj:b,Dj:c});S.Ei.sort((f,g)=>f.Rj<g.Rj)}function Sd(a){S.Ei=S.Ei.filter(b=>b.uj!=a)}function Td(){return navigator.userActivation?navigator.userActivation.isActive:S.oj&&S.Wj.Yi}function Ud(){if(Td()){var a=S.Ei;S.Ei=[];for(var b of a)b.uj(...b.Dj)}}
function Vd(a){if(!a.target)return-4;if(a.li)a.Fj=function(c){++S.oj;S.Wj=a;Ud();a.vi(c);Ud();--S.oj},a.target.addEventListener(a.ki,a.Fj,a.pi),S.mi.push(a);else for(var b=0;b<S.mi.length;++b)S.mi[b].target==a.target&&S.mi[b].ki==a.ki&&Qd(b--);return 0}function Wd(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var S={wk:0,mj:0,pj:0,dj:0,Aj:0,wj:0,jj:0,Fk:0,Tk:0,Ek:0,lj:0,sj:0,zj:0,vj:0,Uk(){for(;S.mi.length;)Qd(S.mi.length-1);S.Ei=[]},oj:0,Ei:[],mi:[],sk:(a,b)=>{for(var c=0;c<S.mi.length;++c)S.mi[c].target!=a||b&&b!=S.mi[c].ki||Qd(c--)},Vk(a){let b=!1;for(let c=0;c<S.mi.length;++c){const d=S.mi[c];d.target===a.target&&d.oi===a.oi&&d.li===a.li&&d.ri===a.ri&&(Qd(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Xd=a=>{for(var b=a.parentNode,
c=[];a!=document.body;){var d=b.children,e;for(e of d)e!=a&&(c.push({node:e,bk:e.style.display}),e.style.display="none");a=b;b=b.parentNode}return c},Yd=null,Zd={},$d=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},ae=[0,globalThis.document??0,globalThis.window??0],U=a=>{a=2<a?a?z(t,a):"":a;return ae[a]||globalThis.document?.querySelector(a)},ce=a=>{var b=bb(a)+1,c=be(b);A(a,t,c,b);return c},de=a=>{var b=V(),c=be(8),d=c+4;a=ce(a.id);if(a=
U(a))u[c>>2]=a.width,u[d>>2]=a.height;c=[u[c>>2],u[d>>2]];X(b);return c},ee=(a,b,c)=>{a=U(a);if(!a)return-4;a.width=b;a.height=c;return 0},fe=(a,b,c)=>{if(a.Ck){var d=V();a=ce(a.id);ee(a,b,c);X(d)}else a.width=b,a.height=c},ge=()=>{var a=devicePixelRatio,b=2==Zd.Li,c=2==Zd.Ri,d=0!=Zd.Li,e=3==Zd.Ri,f=b?Math.round(innerHeight*a):innerHeight,g=b?Math.round(innerWidth*a):innerWidth,k=f,m=Zd.target,n=de(m),q=n[0];n=n[1];if(c){g*n<q*k?k=g*n/q|0:g*n>q*k&&(g=k*q/n|0);var r=(f-k)/2|0}d&&(fe(m,g,k),m.Hi&&m.Hi.wi.viewport(0,
0,g,k));b&&(g=Math.round(g/a*1E4)/1E4,k=Math.round(k/a*1E4)/1E4,r=Math.round(r/a*1E4)/1E4);e?(a=(innerWidth-parseInt(m.style.width))/2,$d(m,(innerHeight-parseInt(m.style.height))/2,a)):(m.style.width=g+"px",m.style.height=k+"px",a=(innerWidth-g)/2,$d(m,r,a));!e&&Zd.si&&y(Zd.si)(37,0,Zd.Ki)},he=a=>{function b(){Dc()||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),fe(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=k,m||(document.body.style.backgroundColor=
"white"),document.body.style.backgroundColor=m,a.style.paddingLeft=n,a.style.paddingRight=q,a.style.paddingTop=r,a.style.paddingBottom=v,a.style.marginLeft=D,a.style.marginRight=N,a.style.marginTop=O,a.style.marginBottom=R,document.body.style.margin=M,document.documentElement.style.overflow=T,document.body.scroll=jc,a.style.Fi=W,a.Hi&&a.Hi.wi.viewport(0,0,d,e),Zd.si&&y(Zd.si)(37,0,Zd.Ki))}var c=de(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,k=a.style.backgroundColor,m=document.body.style.backgroundColor,
n=a.style.paddingLeft,q=a.style.paddingRight,r=a.style.paddingTop,v=a.style.paddingBottom,D=a.style.marginLeft,N=a.style.marginRight,O=a.style.marginTop,R=a.style.marginBottom,M=document.body.style.margin,T=document.documentElement.style.overflow,jc=document.body.scroll,W=a.style.Fi;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b);return b},ie=a=>0>ae.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},je=(a,b)=>{var c=he(a),d=b.Sj?innerWidth:screen.width,
e=b.Sj?innerHeight:screen.height,f=ie(a),g=f.width;f=f.height;var k=de(a),m=k[0];k=k[1];3==b.Ri?($d(a,(e-f)/2,(d-g)/2),d=g,e=f):2==b.Ri&&(d*k<m*e?(g=k*d/m,$d(a,(e-g)/2,0),e=g):(g=m*e/k,$d(a,0,(d-g)/2),d=g));var n;(n=a.style).backgroundColor||(n.backgroundColor="black");let q;(q=document.body.style).backgroundColor||(q.backgroundColor="black");a.style.width=d+"px";a.style.height=e+"px";1==b.Hj&&(a.style.Fi="optimizeSpeed",a.style.Fi="-moz-crisp-edges",a.style.Fi="-o-crisp-edges",a.style.Fi="-webkit-optimize-contrast",
a.style.Fi="optimize-contrast",a.style.Fi="crisp-edges",a.style.Fi="pixelated");n=2==b.Li?devicePixelRatio:1;0!=b.Li&&(b=d*n|0,e=e*n|0,fe(a,b,e),a.Hi&&a.Hi.wi.viewport(0,0,b,e));return c},ke=(a,b)=>{0==b.Ri&&0==b.Li||je(a,b);if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return S.fullscreenEnabled()?-3:-1;Zd=b;b.si&&y(b.si)(37,0,b.Ki);return 0},le=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?
-3:-1;return 0},me=(a,b,c)=>{a=Za(a);a=Hc[a];if(!a)return 0;var d=a.getContext("2d").getImageData(0,0,a.width,a.height),e=rd(a.width*a.height*4);t.set(d.data,e);u[b>>2]=a.width;u[c>>2]=a.height;return e},ne=a=>I.activeTexture(a),oe=(a,b)=>{I.attachShader(J[a],K[b])},pe=(a,b)=>{if(b&&!Xc[b]){var c=I.createBuffer();c.name=b;Xc[b]=c}34962==a?I.Ni=b:34963==a&&(I.Ui=b);35051==a?I.gj=b:35052==a&&(I.xi=b);I.bindBuffer(a,Xc[b])},qe=(a,b)=>{I.bindTexture(a,ad[b])},re=a=>{I.bindVertexArray(bd[a]);a=I.getParameter(34965);
I.Ui=a?a.name|0:0},se=(a,b)=>I.blendFunc(a,b),te=(a,b,c,d)=>{c&&b?I.bufferData(a,t,d,c,b):I.bufferData(a,b,d)},ue=(a,b,c,d)=>{c&&I.bufferSubData(a,b,t,d,c)},ve=a=>I.clear(a),we=(a,b,c,d)=>I.clearColor(a,b,c,d),xe=a=>{I.compileShader(K[a])},ye=(a,b,c,d,e,f,g,k)=>I.copyTexImage2D(a,b,c,d,e,f,g,k),ze=()=>{var a=ld(J),b=I.createProgram();b.name=a;b.bj=b.$i=b.aj=0;b.xj=1;J[a]=b;return a},Ae=a=>{var b=ld(K);K[b]=I.createShader(a);return b},Be=(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Xc[d];e&&(I.deleteBuffer(e),
e.name=0,Xc[d]=null,d==I.Ni&&(I.Ni=0),d==I.Ui&&(I.Ui=0),d==I.gj&&(I.gj=0),d==I.xi&&(I.xi=0))}},Ce=a=>{if(a){var b=J[a];b?(I.deleteProgram(b),b.name=0,J[a]=null):P||=1281}},De=a=>{if(a){var b=K[a];b?(I.deleteShader(b),K[a]=null):P||=1281}},Ee=(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=ad[d];e&&(I.deleteTexture(e),e.name=0,ad[d]=null)}},Fe=(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];I.deleteVertexArray(bd[d]);bd[d]=null}},Ge=a=>I.disable(a),He=(a,b,c)=>{pd(b+c);I.drawArrays(a,b,c);od&&I.bindBuffer(34962,
Xc[I.Ni])},Ie=(a,b,c,d)=>{I.drawArraysInstanced(a,b,c,d)},Je=[],Ke=(a,b)=>{for(var c=Je[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];I.drawBuffers(c)},Le=(a,b,c,d)=>{var e=0;if(!I.Ui){var f=1*fd[c-5120]*b;var g=nd(f);I.bindBuffer(34963,g);I.bufferSubData(34963,0,t.subarray(d,d+f));if(0<b)for(g=0;g<Q.qj;++g)if(f=Q.Bi[g],f.Mi&&f.enabled){switch(c){case 5121:e=Uint8Array;break;case 5123:e=Uint16Array;break;case 5125:e=Uint32Array;break;default:P||=1282;return}e=(new e(t.buffer,d,b)).reduce((k,m)=>Math.max(k,m))+
1;break}d=0}pd(e);I.drawElements(a,b,c,d);od&&I.bindBuffer(34962,Xc[I.Ni]);I.Ui||I.bindBuffer(34963,null)},Me=(a,b,c,d,e)=>{I.drawElementsInstanced(a,b,c,d,e)},Ne=a=>I.enable(a),Oe=a=>{Q.Bi[a].enabled=!0;I.enableVertexAttribArray(a)},Pe=a=>{switch(a){case 34962:a=34964;break;case 34963:a=34965;break;case 35051:a=35053;break;case 35052:a=35055;break;case 35982:a=35983;break;case 36662:a=36662;break;case 36663:a=36663;break;case 35345:a=35368}return(a=I.getParameter(a))?a.name|0:0},Qe=a=>{switch(a){case 34962:case 34963:case 36662:case 36663:case 35051:case 35052:case 35882:case 35982:case 35345:return!0;
default:return!1}},Re=(a,b)=>{md(a,b,"createBuffer",Xc)},Se=(a,b)=>{md(a,b,"createTexture",ad)},Te=(a,b)=>{md(a,b,"createVertexArray",bd)},Ue=a=>I.generateMipmap(a),Ve=(a,b,c,d,e,f,g,k)=>{b=J[b];if(a=I[a](b,c))d=k&&A(a.name,t,k,d),e&&(u[e>>2]=d),f&&(u[f>>2]=a.size),g&&(u[g>>2]=a.type)},We=(a,b)=>{w[a>>2]=b;w[a+4>>2]=(b-w[a>>2])/4294967296},Xe=()=>{var a=Vc(I);return a=a.concat(a.map(b=>"GL_"+b))},Ye=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(P||=1280);return;
case 34814:case 36345:d=0;break;case 34466:var e=I.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>Q.version){P||=1282;return}d=Xe().length;break;case 33307:case 33308:if(2>Q.version){P||=1280;return}d=33307==a?3:0}if(void 0===d)switch(e=I.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":P||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=
0;break;default:P||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:u[b+4*a>>2]=e[a];break;case 2:x[b+4*a>>2]=e[a];break;case 4:p[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){P||=1280;l(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:P||=1280;l(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:We(b,d);break;case 0:u[b>>2]=d;break;case 2:x[b>>2]=d;break;case 4:p[b]=d?1:0}}else P||=1281},Ze=(a,b,c,d)=>{if(c){b=I.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:P||=1280;return}else if(b instanceof WebGLBuffer)a=b.name|0;else{P||=1280;return}break;default:P||=1280;return}switch(d){case 1:We(c,a);break;case 0:u[c>>2]=a;break;case 2:x[c>>2]=a;break;
case 4:p[c]=a?1:0;break;default:ya("internal emscriptenWebGLGetIndexed() error, bad type: "+d)}}else P||=1281},$e=(a,b)=>Ye(a,b,0),af=(a,b,c,d)=>{a=I.getProgramInfoLog(J[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,t,d,b):0;c&&(u[c>>2]=b)},bf=(a,b,c)=>{if(c)if(a>=Wc)P||=1281;else if(a=J[a],35716==b)a=I.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.bj){var d=I.getProgramParameter(a,35718);for(b=0;b<d;++b)a.bj=Math.max(a.bj,I.getActiveUniform(a,
b).name.length+1)}u[c>>2]=a.bj}else if(35722==b){if(!a.$i)for(d=I.getProgramParameter(a,35721),b=0;b<d;++b)a.$i=Math.max(a.$i,I.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.$i}else if(35381==b){if(!a.aj)for(d=I.getProgramParameter(a,35382),b=0;b<d;++b)a.aj=Math.max(a.aj,I.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.aj}else u[c>>2]=I.getProgramParameter(a,b);else P||=1281},cf=(a,b,c)=>{if(c){a=L[a];b=2>Q.version?I.ti.getQueryObjectEXT(a,b):I.getQueryParameter(a,b);var d;"boolean"==typeof b?
d=b?1:0:d=b;We(c,d)}else P||=1281},df=(a,b,c)=>{if(c){a=I.ti.getQueryObjectEXT(L[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else P||=1281},ef=(a,b,c,d)=>{a=I.getShaderInfoLog(K[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,t,d,b):0;c&&(u[c>>2]=b)},ff=(a,b,c)=>{c?35716==b?(a=I.getShaderInfoLog(K[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=I.getShaderSource(K[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=I.getShaderParameter(K[a],b):P||=1281},gf=a=>{var b=gd[a];if(!b){switch(a){case 7939:b=
sd(Xe().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=I.getParameter(a))||(P||=1280);b=b?sd(b):0;break;case 7938:b=sd(`OpenGL ES 3.0 (${I.getParameter(7938)})`);break;case 35724:b=I.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=sd(b);break;default:P||=1280}gd[a]=b}return b},hf=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),jf=a=>{var b=a.Xi,c=a.Uj,d;if(!b){a.Xi=b={};a.Tj={};
var e=I.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=I.getActiveUniform(a,d);var g=f.name;f=f.size;var k=hf(g);k=0<k?g.slice(0,k):g;var m=a.xj;a.xj+=f;c[k]=[f,m];for(g=0;g<f;++g)b[m]=g,a.Tj[m++]=k}}},kf=(a,b)=>{b=b?z(t,b):"";if(a=J[a]){jf(a);var c=a.Xi,d=0,e=b,f=hf(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Uj[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||I.getUniformLocation(a,b)))return d}else P||=1281;return-1},Y=a=>{var b=I.Xj;if(b){var c=b.Xi[a];"number"==typeof c&&(b.Xi[a]=c=I.getUniformLocation(b,
b.Tj[a]+(0<c?`[${c}]`:"")));return c}P||=1282},lf=(a,b,c,d)=>{if(c)if(a=J[a],jf(a),a=I.getUniform(a,Y(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:x[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:x[c+4*b>>2]=a[b]}else P||=1281},mf=(a,b,c,d)=>{if(c)if(Q.Bi[a].enabled&&l("glGetVertexAttrib*v on client-side array: not supported, bad data returned"),a=I.getVertexAttrib(a,b),34975==b)u[c>>2]=a&&a.name;else if("number"==typeof a||
"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:x[c>>2]=a;break;case 5:u[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:x[c+4*b>>2]=a[b];break;case 5:u[c+4*b>>2]=Math.fround(a[b])}else P||=1281},nf=(a,b,c)=>{mf(a,b,c,0)},of=a=>(a=bd[a])?I.isVertexArray(a):0,pf=a=>I.lineWidth(a),qf=a=>{a=J[a];I.linkProgram(a);a.Xi=0;a.Uj={}},rf=(a,b)=>{3317==a?jd=b:3314==a&&(kd=b);I.pixelStorei(a,b)},sf=a=>{a-=5120;return 0==a?p:1==a?t:2==a?ra:4==a?u:6==
a?x:5==a||28922==a||28520==a||30779==a||30782==a?w:sa},tf=(a,b,c,d,e,f,g)=>{if(I.gj)I.readPixels(a,b,c,d,e,f,g);else{var k=sf(f);g>>>=31-Math.clz32(k.BYTES_PER_ELEMENT);I.readPixels(a,b,c,d,e,f,k,g)}},uf=(a,b,c,d)=>{for(var e="",f=0;f<b;++f)e+=pc(w[c+4*f>>2],d?w[d+4*f>>2]:void 0);I.shaderSource(K[a],e)},vf=(a,b,c,d,e)=>{a=sf(a);b=d*((kd||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+jd-1&-jd);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),
e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},wf=(a,b,c,d,e,f,g,k,m)=>{if(I.xi)I.texImage2D(a,b,c,d,e,f,g,k,m);else if(m){var n=sf(k);m>>>=31-Math.clz32(n.BYTES_PER_ELEMENT);I.texImage2D(a,b,c,d,e,f,g,k,n,m)}else n=m?vf(k,g,d,e,m):null,I.texImage2D(a,b,c,d,e,f,g,k,n)},xf=(a,b,c)=>I.texParameteri(a,b,c),yf=(a,b)=>{I.uniform1f(Y(a),b)},zf=(a,b,c)=>{b&&I.uniform1fv(Y(a),x,c>>2,b)},Af=(a,b)=>{I.uniform1i(Y(a),b)},Bf=(a,b,c)=>{b&&I.uniform1iv(Y(a),u,c>>2,b)},Cf=(a,b,c)=>{b&&I.uniform2fv(Y(a),x,c>>2,2*b)},
Df=(a,b,c)=>{b&&I.uniform3fv(Y(a),x,c>>2,3*b)},Ef=(a,b,c)=>{b&&I.uniform4fv(Y(a),x,c>>2,4*b)},Ff=(a,b,c,d)=>{b&&I.uniformMatrix3fv(Y(a),!!c,x,d>>2,9*b)},Gf=(a,b,c,d)=>{b&&I.uniformMatrix4fv(Y(a),!!c,x,d>>2,16*b)},Hf=a=>{a=J[a];I.useProgram(a);I.Xj=a},If=(a,b)=>{I.vertexAttribDivisor(a,b)},Jf=(a,b,c,d,e,f)=>{var g=Q.Bi[a];I.Ni?(g.Mi=!1,I.vertexAttribPointer(a,b,c,!!d,e,f)):(g.size=b,g.type=c,g.rj=d,g.stride=e,g.ii=f,g.Mi=!0,g.yj=function(k,m,n,q,r,v){this.vertexAttribPointer(k,m,n,q,r,v)})},Kf=(a,
b,c,d)=>I.viewport(a,b,c,d),Lf=(a,b)=>{if(!S.fullscreenEnabled())return-1;a=U(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Td()?ke(a,b):b.ak?(Rd(ke,1,[a,b]),1):-2:-3:-4},Mf=(a,b)=>{var c={target:U(2),ki:"beforeunload",oi:28,ri:a,li:b,vi:d=>{var e=y(b)(28,0,a);e&&=e?z(t,e):"";if(e)return d.preventDefault(),d.returnValue=e},pi:!0};return Vd(c)},Nf=(a,b,c,d,e,f)=>{S.jj||(S.jj=rd(256));a={target:U(a),ki:f,oi:e,ri:b,li:d,vi:g=>{var k=g.target.id?g.target.id:"",m=S.jj;A(Wd(g.target),t,m+0,
128);A(k,t,m+128,128);y(d)(e,m,b)&&g.preventDefault()},pi:c};return Vd(a)},Of=(a,b,c,d,e)=>{S.lj||(S.lj=rd(276));return Vd({target:a,ki:e,oi:19,ri:b,li:d,vi:f=>{var g=S.lj,k=Dc(),m=!!k;p[g]=m;p[g+1]=S.fullscreenEnabled();var n=m?k:S.rk,q=n?.id||"";A(Wd(n),t,g+2,128);A(q,t,g+130,128);u[g+260>>2]=n?n.clientWidth:0;u[g+264>>2]=n?n.clientHeight:0;u[g+268>>2]=screen.width;u[g+272>>2]=screen.height;m&&(S.rk=k);y(d)(19,g,b)&&f.preventDefault()},pi:c})},Pf=(a,b,c,d,e)=>{S.mj||(S.mj=rd(1240));b={target:U(2),
Yi:!0,ki:e,oi:d,ri:a,li:c,vi:f=>{var g=S.mj,k=f.gamepad;ta[g>>3]=k.timestamp;for(var m=0;m<k.axes.length;++m)ta[g+8*m+16>>3]=k.axes[m];for(m=0;m<k.buttons.length;++m)ta[g+8*m+528>>3]="object"==typeof k.buttons[m]?k.buttons[m].value:k.buttons[m];for(m=0;m<k.buttons.length;++m)p[g+m+1040]="object"==typeof k.buttons[m]?k.buttons[m].pressed:1==k.buttons[m];p[g+1104]=k.connected;u[g+1108>>2]=k.index;u[g+8>>2]=k.axes.length;u[g+12>>2]=k.buttons.length;A(k.id,t,g+1112,64);A(k.mapping,t,g+1176,64);y(c)(d,
g,a)&&f.preventDefault()},pi:b};return Vd(b)},Qf=()=>{try{if(navigator.getGamepads)return(S.Nk=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},Rf=(a,b,c,d,e,f)=>{S.pj||(S.pj=rd(160));a={target:U(a),ki:f,oi:e,ri:b,li:d,vi:g=>{var k=S.pj;ta[k>>3]=g.timeStamp;var m=k>>2;u[m+2]=g.location;p[k+12]=g.ctrlKey;p[k+13]=g.shiftKey;p[k+14]=g.altKey;p[k+15]=g.metaKey;p[k+16]=g.repeat;u[m+5]=g.charCode;u[m+6]=g.keyCode;u[m+7]=g.which;A(g.key||"",t,k+32,32);A(g.code||"",t,k+64,32);A(g.char||
"",t,k+96,32);A(g.locale||"",t,k+128,32);y(d)(e,k,b)&&g.preventDefault()},pi:c};return Vd(a)},Sf=(a,b,c)=>{ta[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;p[a+24]=b.ctrlKey;p[a+25]=b.shiftKey;p[a+26]=b.altKey;p[a+27]=b.metaKey;ra[2*d+14]=b.button;ra[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=ie(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},Tf=(a,b,c,d,e,f)=>{S.dj||(S.dj=rd(64));a=U(a);return Vd({target:a,Yi:"mousemove"!=
f&&"mouseenter"!=f&&"mouseleave"!=f,ki:f,oi:e,ri:b,li:d,vi:g=>{Sf(S.dj,g,a);y(d)(e,S.dj,b)&&g.preventDefault()},pi:c})},Uf=(a,b,c,d)=>{S.sj||(S.sj=rd(257));return Vd({target:a,ki:"pointerlockchange",oi:20,ri:b,li:d,vi:e=>{var f=S.sj,g=document.pointerLockElement;p[f]=!!g;var k=g?.id||"";A(Wd(g),t,f+1,128);A(k,t,f+129,128);y(d)(20,f,b)&&e.preventDefault()},pi:c})},Vf=(a,b,c,d)=>{S.wj||(S.wj=rd(36));a=U(a);return Vd({target:a,ki:"resize",oi:10,ri:b,li:d,vi:e=>{if(e.target==a){var f=document.body;if(f){var g=
S.wj;u[g>>2]=0;u[g+4>>2]=f.clientWidth;u[g+8>>2]=f.clientHeight;u[g+12>>2]=innerWidth;u[g+16>>2]=innerHeight;u[g+20>>2]=outerWidth;u[g+24>>2]=outerHeight;u[g+28>>2]=pageXOffset|0;u[g+32>>2]=pageYOffset|0;y(d)(10,g,b)&&e.preventDefault()}}},pi:c})},Wf=(a,b,c,d,e,f)=>{S.vj||(S.vj=rd(1552));a=U(a);return Vd({target:a,Yi:"touchstart"==f||"touchend"==f,ki:f,oi:e,ri:b,li:d,vi:g=>{var k={},m=g.touches;for(var n of m)n.Lj=n.Qj=0,k[n.identifier]=n;for(var q of g.changedTouches)q.Lj=1,k[q.identifier]=q;for(var r of g.targetTouches)k[r.identifier].Qj=
1;m=S.vj;ta[m>>3]=g.timeStamp;p[m+12]=g.ctrlKey;p[m+13]=g.shiftKey;p[m+14]=g.altKey;p[m+15]=g.metaKey;n=m+16;q=ie(a);r=0;for(let v of Object.values(k))if(k=n>>2,u[k]=v.identifier,u[k+1]=v.screenX,u[k+2]=v.screenY,u[k+3]=v.clientX,u[k+4]=v.clientY,u[k+5]=v.pageX,u[k+6]=v.pageY,p[n+28]=v.Lj,p[n+29]=v.Qj,u[k+8]=v.clientX-(q.left|0),u[k+9]=v.clientY-(q.top|0),n+=48,31<++r)break;u[m+8>>2]=r;y(d)(e,m,b)&&g.preventDefault()},pi:c})},Xf=(a,b,c)=>{var d=ae[1];S.zj||(S.zj=rd(8));return Vd({target:d,ki:"visibilitychange",
oi:21,ri:a,li:c,vi:e=>{var f=S.zj,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);p[f]=document.hidden;u[f+4>>2]=g;y(c)(21,f,a)&&e.preventDefault()},pi:b})},Yf=(a,b,c,d)=>{S.Aj||(S.Aj=rd(96));return Vd({target:a,Yi:!0,ki:"wheel",oi:9,ri:b,li:d,vi:e=>{var f=S.Aj;Sf(f,e,a);ta[f+64>>3]=e.deltaX;ta[f+72>>3]=e.deltaY;ta[f+80>>3]=e.deltaZ;u[f+88>>2]=e.deltaMode;y(d)(9,f,b)&&e.preventDefault()},pi:c})},Zf={},ag=()=>{if(!$f){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",
PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Zf)void 0===Zf[b]?delete a[b]:a[b]=Zf[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);$f=c}return $f},$f,bg=(a,b,c,d)=>{var e={string:n=>{var q=0;null!==n&&void 0!==n&&0!==n&&(q=ce(n));return q},array:n=>{var q=be(n.length);p.set(n,q);return q}};a=h["_"+a];var f=[],g=0;if(d)for(var k=0;k<d.length;k++){var m=e[c[k]];m?(0===g&&(g=V()),f[k]=m(d[k])):f[k]=d[k]}c=a(...f);
return c=function(n){0!==g&&X(g);return"string"===b?n?z(t,n):"":"boolean"===b?!!n:n}(c)};Db=Array(4096);Vb(C,"/");Yb("/tmp");Yb("/home");Yb("/home/web_user");(function(){Yb("/dev");fb(259,{read:()=>0,write:(d,e,f,g)=>g,yi:()=>0});Zb("/dev/null",259);eb(1280,hb);eb(1536,ib);Zb("/dev/tty",1280);Zb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Xa(a),b=a.byteLength);return a[--b]};mc("/dev","random",c);mc("/dev","urandom",c);Yb("/dev/shm");Yb("/dev/shm/tmp")})();
(function(){Yb("/proc");var a=Yb("/proc/self");Yb("/proc/self/fd");Vb({Ci(){var b=mb(a,"fd",16895,73);b.fi={yi:C.fi.yi};b.ei={lookup(c,d){c=+d;var e=Rb(c);c={parent:null,Ci:{Pj:"fake"},ei:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(Bb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();var cg=()=>{if(Q){var a=Q.Ti;Q.Ti=Q.Wi;Q.Wi=a;a=Q.Gi;Q.Gi=Q.fj;Q.fj=a;for(a=0;21>=a;++a)Q.Gi[a]=0}};"undefined"!=typeof Ad&&Gd.push(cg);
h.requestAnimationFrame=Md;h.pauseMainLoop=Kd;h.resumeMainLoop=function(){td++;var a=Cd,b=Dd,c=ud;ud=null;Jd(c,0,!1,vd,!0);Id(a,b);Ed()};h.preMainLoop&&Gd.push(h.preMainLoop);h.postMainLoop&&Hd.push(h.postMainLoop);for(let a=0;32>a;++a)Je.push(Array(a));h.noExitRuntime&&(Ia=h.noExitRuntime);h.preloadPlugins&&(vb=h.preloadPlugins);h.print&&(la=h.print);h.printErr&&(l=h.printErr);h.wasmBinary&&(ma=h.wasmBinary);h.arguments&&(da=h.arguments);h.thisProgram&&(ea=h.thisProgram);
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();h.addRunDependency=ub;h.removeRunDependency=tb;h.ccall=bg;h.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?h["_"+a]:(...f)=>bg(a,b,c,f,d)};h.UTF8ToString=pc;h.createContext=Kc;
h.FS_preloadFile=async(a,b,c,d,e,f,g,k)=>{var m=b?Za(Ta(a+"/"+b)):a,n=`cp ${m}`;ub(n);try{var q=c;"string"==typeof c&&(q=await qb(c));q=await yb(q,m);k?.();f||lc(a,b,q,d,e,g)}finally{tb(n)}};h.FS_unlink=(...a)=>bc(...a);h.FS_createPath=(...a)=>ic(...a);h.FS_createDevice=(...a)=>mc(...a);h.FS_createDataFile=(...a)=>lc(...a);h.FS_createLazyFile=(...a)=>oc(...a);
var dg={350049:()=>window.innerWidth,350079:()=>window.innerHeight,350110:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.Vj!==h.canvas&&(d.Zi=Kc(h.canvas,!1,!0),d.Vj=h.canvas);if(d.w!==a||d.h!==b||d.fk!==d.Zi)d.image=d.Zi.createImageData(a,b),d.w=a,d.h=b,d.fk=d.Zi;a=d.image.data;b=c/4;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=u[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.Zj!==a&&(d.Yj=new Int32Array(a.buffer),
d.$j=new Uint8Array(a.buffer),d.Zj=a),a=d.Yj,c=a.length,a.set(u.subarray(b,b+c)),a=d.$j,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.Zi.putImageData(d.image,0,0)},351576:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e/=4;var k=0,m;if("undefined"!==typeof CanvasPixelArray&&
b instanceof CanvasPixelArray)for(m=b.length;k<m;){var n=u[e];b[k]=n&255;b[k+1]=n>>8&255;b[k+2]=n>>16&255;b[k+3]=n>>24&255;e++;k+=4}else b=new Int32Array(b.buffer),m=b.length,b.set(u.subarray(e,e+m));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=rd(c.length+1);A(c,t,d,c.length+1);return d},352564:a=>{h.canvas&&(h.canvas.style.cursor=a?z(t,a):"")},352647:()=>{h.canvas&&(h.canvas.style.cursor="none")}},eg,rd,fg,gg,jb,hg,Z,Pa,X,be,V,
ig,jg,Qa,kg,xa,Ka,Qg={Kb:(a,b)=>y(a)(b),m:a=>{var b=new Oa(a);0==p[b.ii+12]&&(p[b.ii+12]=1,Ma--);p[b.ii+13]=0;La.push(b);jg(a);return kg(a)},w:()=>{Z(0,0);var a=La.pop();ig(a.Gj);Na=0},a:()=>Ra([]),k:a=>Ra([a]),l:(a,b)=>Ra([a,b]),n:(a,b,c)=>Ra([a,b,c]),Fa:()=>{var a=La.pop();a||ya("no exception to throw");var b=a.Gj;0==p[a.ii+13]&&(La.push(a),p[a.ii+13]=1,p[a.ii+12]=0,Ma++);Na=b;throw Na;},v:(a,b,c)=>{var d=new Oa(a);w[d.ii+16>>2]=0;w[d.ii+4>>2]=b;w[d.ii+8>>2]=c;Na=a;Ma++;throw Na;},Qb:()=>Ma,e:a=>
{Na||=a;throw Na;},mc:function(a){try{a=a?z(t,a):"";var b=Jb(a,{Oi:!0});if(null===b.node)throw new B(44);if(!E(b.node.mode))throw new B(54);var c=Mb(b.node,"x");if(c)throw new B(c);Ya=b.path;return 0}catch(d){if("undefined"==typeof F||"ErrnoError"!==d.name)throw d;return-d.hi}},da:function(a,b,c){sc=c;try{var d=Rb(a);switch(b){case 0:var e=tc();if(0>e)break;for(;Bb[e];)e++;return Tb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=tc(),d.flags|=e,0;case 12:return e=tc(),ra[e+0>>
1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof F||"ErrnoError"!==f.name)throw f;return-f.hi}},hc:function(a,b){try{var c=Rb(a),d=c.node,e=c.fi.ui;a=e?c:d;e??=d.ei.ui;Qb(e,63);var f=e(a);return rc(b,f)}catch(g){if("undefined"==typeof F||"ErrnoError"!==g.name)throw g;return-g.hi}},cc:function(a,b){try{if(0===b)return-28;var c=Ya,d=bb(c)+1;if(b<d)return-68;A(c,t,a,b);return d}catch(e){if("undefined"==typeof F||"ErrnoError"!==e.name)throw e;return-e.hi}},Rb:function(a,b,c){try{var d=
Rb(a);if(!d.Ii){var e=Jb(d.path,{Oi:!0}).node;var f=Qb(e.ei.readdir,54)(e);d.Ii=f}a=0;var g=gc(d,0,1),k=Math.floor(g/280),m=Math.min(d.Ii.length,k+Math.floor(c/280));for(c=k;c<m;c++){var n=d.Ii[c];if("."===n){var q=d.node.id;var r=4}else if(".."===n)q=Jb(d.path,{parent:!0}).node.id,r=4;else{try{var v=nb(d.node,n)}catch(D){if(28===D?.hi)continue;throw D;}q=v.id;r=8192===(v.mode&61440)?2:E(v.mode)?4:40960===(v.mode&61440)?10:8}ua[b+a>>3]=BigInt(q);ua[b+a+8>>3]=BigInt(280*(c+1));ra[b+a+16>>1]=280;p[b+
a+18]=r;A(n,t,b+a+19,256);a+=280}gc(d,280*c,0);return a}catch(D){if("undefined"==typeof F||"ErrnoError"!==D.name)throw D;return-D.hi}},jc:function(a,b,c){sc=c;try{var d=Rb(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Di.ik){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=tc();u[e>>2]=25856;u[e+4>>2]=5;u[e+8>>2]=191;u[e+12>>2]=35387;for(var f=0;32>f;f++)p[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?
0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Di.jk)for(e=tc(),a=[],f=0;32>f;f++)a.push(p[e+f+17]);return 0;case 21519:if(!d.tty)return-59;e=tc();return u[e>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:e=tc();if(!d.fi.hk)throw new B(59);return d.fi.hk(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Di.kk&&(f=[24,80],e=tc(),ra[e>>1]=f[0],ra[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==
typeof F||"ErrnoError"!==g.name)throw g;return-g.hi}},fc:function(a,b){try{return a=a?z(t,a):"",rc(b,cc(a,!0))}catch(c){if("undefined"==typeof F||"ErrnoError"!==c.name)throw c;return-c.hi}},dc:function(a,b,c,d){try{b=b?z(t,b):"";var e=d&256;b=qc(a,b,d&4096);return rc(c,e?cc(b,!0):cc(b))}catch(f){if("undefined"==typeof F||"ErrnoError"!==f.name)throw f;return-f.hi}},ya:function(a,b,c,d){sc=d;try{b=b?z(t,b):"";b=qc(a,b);var e=d?tc():0;return ec(b,c,e).fd}catch(f){if("undefined"==typeof F||"ErrnoError"!==
f.name)throw f;return-f.hi}},Pb:function(a,b,c,d){try{b=b?z(t,b):"";b=qc(a,b);if(0>=d)return-28;var e=Jb(b).node;if(!e)throw new B(44);if(!e.ei.readlink)throw new B(28);var f=e.ei.readlink(e);var g=Math.min(d,bb(f)),k=p[c+g];A(f,t,c,d+1);p[c+g]=k;return g}catch(m){if("undefined"==typeof F||"ErrnoError"!==m.name)throw m;return-m.hi}},Ub:function(a){try{return a=a?z(t,a):"",ac(a),0}catch(b){if("undefined"==typeof F||"ErrnoError"!==b.name)throw b;return-b.hi}},gc:function(a,b){try{return a=a?z(t,a):
"",rc(b,cc(a))}catch(c){if("undefined"==typeof F||"ErrnoError"!==c.name)throw c;return-c.hi}},Vb:function(a,b,c){try{b=b?z(t,b):"";b=qc(a,b);if(c)if(512===c)ac(b);else return-28;else bc(b);return 0}catch(d){if("undefined"==typeof F||"ErrnoError"!==d.name)throw d;return-d.hi}},nc:()=>ya(""),Nb:()=>{Ia=!1;uc=0},Tb:a=>{if(ca){if(!a)return 1;a=a?z(t,a):"";if(!a.length)return 0;a=require("child_process").Xk(a,[],{Wk:!0,stdio:"inherit"});var b=(c,d)=>c<<8|d;return null===a.status?b(0,(c=>{switch(c){case "SIGHUP":return 1;
case "SIGQUIT":return 3;case "SIGFPE":return 8;case "SIGKILL":return 9;case "SIGALRM":return 14;case "SIGTERM":return 15;default:return 2}})(a.signal)):a.status<<8|0}return a?-52:0},Ib:()=>{throw Infinity;},Zb:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);u[b>>2]=a.getSeconds();u[b+4>>2]=a.getMinutes();u[b+8>>2]=a.getHours();u[b+12>>2]=a.getDate();u[b+16>>2]=a.getMonth();u[b+20>>2]=a.getFullYear()-1900;u[b+24>>2]=a.getDay();u[b+28>>2]=(vc(a.getFullYear())?
wc:xc)[a.getMonth()]+a.getDate()-1|0;u[b+36>>2]=-(60*a.getTimezoneOffset());var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset(),d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();u[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},_b:function(a){var b=new Date(u[a+20>>2]+1900,u[a+16>>2],u[a+12>>2],u[a+8>>2],u[a+4>>2],u[a>>2],0),c=u[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),g=Math.min(f,
e);0>c?u[a+32>>2]=Number(e!=f&&g==d):0<c!=(g==d)&&(e=Math.max(f,e),b.setTime(b.getTime()+6E4*((0<c?g:e)-d)));u[a+24>>2]=b.getDay();u[a+28>>2]=(vc(b.getFullYear())?wc:xc)[b.getMonth()]+b.getDate()-1|0;u[a>>2]=b.getSeconds();u[a+4>>2]=b.getMinutes();u[a+8>>2]=b.getHours();u[a+12>>2]=b.getDate();u[a+16>>2]=b.getMonth();u[a+20>>2]=b.getYear();a=b.getTime();return BigInt(isNaN(a)?-1:a/1E3)},Xb:function(a,b,c,d,e,f,g){e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);try{var k=Rb(d);if(0!==(b&2)&&
0===(c&2)&&2!==(k.flags&2097155))throw new B(2);if(1===(k.flags&2097155))throw new B(2);if(!k.fi.Vi)throw new B(43);if(!a)throw new B(28);var m=k.fi.Vi(k,a,e,b,c);var n=m.ii;u[f>>2]=m.Cj;w[g>>2]=n;return 0}catch(q){if("undefined"==typeof F||"ErrnoError"!==q.name)throw q;return-q.hi}},Yb:function(a,b,c,d,e,f){f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var g=Rb(e);if(c&2){c=f;if(32768!==(g.node.mode&61440))throw new B(43);if(!(d&2)){var k=t.slice(a,a+b);g.fi.ej&&g.fi.ej(g,k,c,b,d)}}}catch(m){if("undefined"==
typeof F||"ErrnoError"!==m.name)throw m;return-m.hi}},Ob:(a,b)=>{yc[a]&&(clearTimeout(yc[a].id),delete yc[a]);if(!b)return 0;var c=setTimeout(()=>{delete yc[a];Cc(()=>hg(a,performance.now()))},b);yc[a]={id:c,Yk:b};return 0},oc:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();w[a>>2]=60*Math.max(f,e);u[b>>2]=Number(f!=e);b=g=>{var k=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,
"0")}`};a=b(f);b=b(e);e<f?(A(a,t,c,17),A(b,t,d,17)):(A(a,t,d,17),A(b,t,c,17))},lc:function(a,b,c){if(!(0<=a&&3>=a))return 28;ua[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},ab:a=>{if(12448==a)return G=12288,1;G=12300;return 0},lb:(a,b,c,d,e)=>{if(62E3!=a)G=12296,c=0;else{if(b)for(;;){a=u[b>>2];if(12321==a)H.alpha=0<u[b+4>>2];else if(12325==a)H.depth=0<u[b+4>>2];else if(12326==a)H.stencil=0<u[b+4>>2];else if(12337==a)a=u[b+4>>2],H.antialias=0<a;else if(12338==a)a=u[b+
4>>2],H.antialias=1==a;else if(12544==a)H.Ok=12547!=u[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(u[e>>2]=1),c&&0<d&&(w[c>>2]=62002),G=12288,c=1):(G=12300,c=0)}return c},jb:(a,b,c,d)=>{if(62E3!=a)return G=12296,0;for(a=1;;){b=u[d>>2];if(12440==b)a=u[d+4>>2];else if(12344==b)break;else return G=12292,0;d+=8}if(2>a||3<a)return G=12293,0;H.Oj=a-1;H.Qk=0;Uc=Mc(h.canvas,H);if(0!=Uc)return G=12288,Oc(Uc),Gc.forEach(e=>e()),Oc(null),62004;G=12297;return 0},hb:(a,b)=>{if(62E3!=a)return G=12296,0;if(62002!=
b)return G=12293,0;G=12288;return 62006},ib:(a,b)=>{if(62E3!=a)return G=12296,0;if(62004!=b)return G=12294,0;a=Uc;Q===Nc[a]&&(Q=null);"object"==typeof S&&S.sk(Nc[a].wi.canvas);Nc[a]?.wi.canvas&&(Nc[a].wi.canvas.Hi=void 0);Nc[a]=null;G=12288;Qc==b&&(Qc=0);return 1},gb:(a,b)=>{if(62E3!=a)return G=12296,0;if(62006!=b)return G=12301,1;Rc==b&&(Rc=0);Sc==b&&(Sc=0);G=12288;return 1},kb:(a,b,c,d)=>{if(62E3!=a)return G=12296,0;if(62002!=b)return G=12293,0;if(!d)return G=12300,0;G=12288;switch(c){case 12320:return u[d>>
2]=H.alpha?32:24,1;case 12321:return u[d>>2]=H.alpha?8:0,1;case 12322:return u[d>>2]=8,1;case 12323:return u[d>>2]=8,1;case 12324:return u[d>>2]=8,1;case 12325:return u[d>>2]=H.depth?24:0,1;case 12326:return u[d>>2]=H.stencil?8:0,1;case 12327:return u[d>>2]=12344,1;case 12328:return u[d>>2]=62002,1;case 12329:return u[d>>2]=0,1;case 12330:return u[d>>2]=4096,1;case 12331:return u[d>>2]=16777216,1;case 12332:return u[d>>2]=4096,1;case 12333:return u[d>>2]=0,1;case 12334:return u[d>>2]=0,1;case 12335:return u[d>>
2]=12344,1;case 12337:return u[d>>2]=H.antialias?4:0,1;case 12338:return u[d>>2]=H.antialias?1:0,1;case 12339:return u[d>>2]=4,1;case 12340:return u[d>>2]=12344,1;case 12341:case 12342:case 12343:return u[d>>2]=-1,1;case 12345:case 12346:return u[d>>2]=0,1;case 12347:return u[d>>2]=0,1;case 12348:return u[d>>2]=1;case 12349:case 12350:return u[d>>2]=0,1;case 12351:return u[d>>2]=12430,1;case 12352:return u[d>>2]=4,1;case 12354:return u[d>>2]=0,1;default:return G=12292,0}},na:a=>{G=12288;return 0!=
a&&1!=a?0:62E3},_a:()=>G,nb:(a,b,c)=>{if(62E3!=a)return G=12296,0;b&&(u[b>>2]=1);c&&(u[c>>2]=4);Pc=!0;G=12288;return 1},fb:(a,b,c,d)=>{if(62E3!=a)return G=12296,0;if(0!=d&&62004!=d)return G=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return G=12301,0;Oc(d?Uc:null);Qc=d;Sc=b;Rc=c;G=12288;return 1},$a:(a,b)=>{if(62E3!=a)return G=12296,0;G=12288;if(Tc[b])return Tc[b];switch(b){case 12371:a=sd("Emscripten");break;case 12372:a=sd("1.4 Emscripten EGL");break;case 12373:a=sd("");break;case 12429:a=sd("OpenGL_ES");
break;default:return G=12300,0}return Tc[b]=a},eb:()=>{if(Pc)if(I)if(I.isContextLost())G=12302;else return G=12288,1;else G=12290;else G=12289;return 0},db:(a,b)=>{if(62E3!=a)return G=12296,0;0==b?Id(0,0):Id(1,b);G=12288;return 1},mb:a=>{if(62E3!=a)return G=12296,0;Sc=Rc=Qc=0;Pc=!1;G=12288;return 1},bb:()=>{G=12288;return 1},cb:()=>{G=12288;return 1},P:(a,b,c)=>{b=Pd(b,c);return dg[a](...b)},Ya:(a,b,c)=>{b=Pd(b,c);return dg[a](...b)},ga:()=>{Kd();ud=null},za:()=>Date.now(),_d:(a,b)=>{a=U(a);if(!a)return-4;
var c={Ri:u[b>>2],Li:u[b+4>>2],Hj:u[b+8>>2],si:u[b+12>>2],Ki:u[b+16>>2],target:a,Sj:!0},d=je(a,c);document.documentElement.style.overflow="hidden";document.body.scroll="no";document.body.style.margin="0px";var e=Xd(a);Yd=function(){d();for(var f of e)f.node.style.display=f.bk;removeEventListener("resize",ge);c.si&&y(c.si)(37,0,c.Ki);Zd=0};Zd=c;addEventListener("resize",ge);c.si&&y(c.si)(37,0,c.Ki);return 0},Jh:()=>{if(!S.fullscreenEnabled())return-1;Sd(ke);var a=ae[1];if(a.exitFullscreen)a.fullscreenElement&&
a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Xa:()=>{Sd(le);if(!document.exitPointerLock)return-1;document.exitPointerLock();return 0},Pd:()=>{Yd?.();Yd=null;return 0},O:()=>globalThis.devicePixelRatio??1,D:(a,b,c)=>{a=U(a);if(!a)return-4;a=ie(a);ta[b>>3]=a.width;ta[c>>3]=a.height;return 0},ca:()=>performance.now(),rb:(a,b,c)=>me(a?z(t,a):"",b,c),qb:(a,b,c)=>{a=gg(a);return(a=Bb[a])?me(a.path,b,c):0},Za:(a,b)=>{u[a>>
2]=screen.width;u[b>>2]=screen.height},ph:ne,oh:oe,ie:(a,b)=>{I.beginQuery(a,L[b])},Fh:(a,b)=>{I.ti.beginQueryEXT(a,L[b])},Ld:a=>I.beginTransformFeedback(a),nh:(a,b,c)=>{I.bindAttribLocation(J[a],b,c?z(t,c):"")},mh:pe,Id:(a,b,c)=>{I.bindBufferBase(a,b,Xc[c])},Jd:(a,b,c,d,e)=>{I.bindBufferRange(a,b,Xc[c],d,e)},lh:(a,b)=>{I.bindFramebuffer(a,Zc[b])},kh:(a,b)=>{I.bindRenderbuffer(a,$c[b])},Nc:(a,b)=>{I.bindSampler(a,cd[b])},jh:qe,Fc:(a,b)=>{I.bindTransformFeedback(a,dd[b])},Rd:re,xh:re,ih:(a,b,c,d)=>
I.blendColor(a,b,c,d),hh:a=>I.blendEquation(a),gh:(a,b)=>I.blendEquationSeparate(a,b),fh:se,eh:(a,b,c,d)=>I.blendFuncSeparate(a,b,c,d),Wd:(a,b,c,d,e,f,g,k,m,n)=>I.blitFramebuffer(a,b,c,d,e,f,g,k,m,n),dh:te,ch:ue,bh:a=>I.checkFramebufferStatus(a),ah:ve,kd:(a,b,c,d)=>I.clearBufferfi(a,b,c,d),ld:(a,b,c)=>{I.clearBufferfv(a,b,x,c>>2)},nd:(a,b,c)=>{I.clearBufferiv(a,b,u,c>>2)},md:(a,b,c)=>{I.clearBufferuiv(a,b,w,c>>2)},$g:we,_g:a=>I.clearDepth(a),Zg:a=>I.clearStencil(a),Xc:(a,b,c)=>{c=Number(c);return I.clientWaitSync(ed[a],
b,c)},De:(a,b)=>{I.dk.clipControlEXT(a,b)},Yg:(a,b,c,d)=>{I.colorMask(!!a,!!b,!!c,!!d)},Xg:xe,Wg:(a,b,c,d,e,f,g,k)=>{I.xi||!g?I.compressedTexImage2D(a,b,c,d,e,f,g,k):I.compressedTexImage2D(a,b,c,d,e,f,t,k,g)},ne:(a,b,c,d,e,f,g,k,m)=>{I.xi?I.compressedTexImage3D(a,b,c,d,e,f,g,k,m):I.compressedTexImage3D(a,b,c,d,e,f,g,t,m,k)},Vg:(a,b,c,d,e,f,g,k,m)=>{I.xi||!k?I.compressedTexSubImage2D(a,b,c,d,e,f,g,k,m):I.compressedTexSubImage2D(a,b,c,d,e,f,g,t,m,k)},me:(a,b,c,d,e,f,g,k,m,n,q)=>{I.xi?I.compressedTexSubImage3D(a,
b,c,d,e,f,g,k,m,n,q):I.compressedTexSubImage3D(a,b,c,d,e,f,g,k,m,t,q,n)},hd:(a,b,c,d,e)=>I.copyBufferSubData(a,b,c,d,e),Ug:ye,Tg:(a,b,c,d,e,f,g,k)=>I.copyTexSubImage2D(a,b,c,d,e,f,g,k),oe:(a,b,c,d,e,f,g,k,m)=>I.copyTexSubImage3D(a,b,c,d,e,f,g,k,m),Sg:ze,Rg:Ae,Qg:a=>I.cullFace(a),Pg:Be,Og:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=Zc[d];e&&(I.deleteFramebuffer(e),e.name=0,Zc[d]=null)}},Ng:Ce,ke:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=L[d];e&&(I.deleteQuery(e),L[d]=null)}},Hh:(a,b)=>
{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=L[d];e&&(I.ti.deleteQueryEXT(e),L[d]=null)}},Mg:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=$c[d];e&&(I.deleteRenderbuffer(e),e.name=0,$c[d]=null)}},Pc:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=cd[d];e&&(I.deleteSampler(e),e.name=0,cd[d]=null)}},Lg:De,Yc:a=>{if(a){var b=ed[a];b?(I.deleteSync(b),b.name=0,ed[a]=null):P||=1281}},Kg:Ee,Ec:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=dd[d];e&&(I.deleteTransformFeedback(e),e.name=0,dd[d]=null)}},
Qd:Fe,wh:Fe,Jg:a=>I.depthFunc(a),Ig:a=>{I.depthMask(!!a)},Hg:(a,b)=>I.depthRange(a,b),Gg:(a,b)=>{I.detachShader(J[a],K[b])},Fg:Ge,Eg:a=>{Q.Bi[a].enabled=!1;I.disableVertexAttribArray(a)},Dg:He,ad:Ie,sh:Ie,ye:Ie,ze:Ie,pc:Ie,ce:Ke,ue:Ke,th:Ke,Cg:Le,$c:Me,rh:Me,ve:Me,we:Me,xe:Me,re:(a,b,c,d,e,f)=>{Le(a,d,e,f)},Bg:Ne,Ag:Oe,he:a=>I.endQuery(a),Eh:a=>{I.ti.endQueryEXT(a)},Kd:()=>I.endTransformFeedback(),_c:(a,b)=>(a=I.fenceSync(a,b))?(b=ld(ed),a.name=b,ed[b]=a,b):0,zg:()=>I.finish(),yg:()=>I.flush(),Sd:(a,
b,c)=>{if(Qe(a)){var d=Yc[Pe(a)];d?d.Bj&16?0>b||0>c||b+c>d.length?(P||=1281,l("invalid range in glFlushMappedBufferRange")):I.bufferSubData(a,d.offset,t.subarray(d.Ji+b,d.Ji+b+c)):(P||=1282,l("buffer was not mapped with GL_MAP_FLUSH_EXPLICIT_BIT in glFlushMappedBufferRange")):(P||=1282,l("buffer was never mapped in glFlushMappedBufferRange"))}else P||=1280,l("GL_INVALID_ENUM in glFlushMappedBufferRange")},xg:(a,b,c,d)=>{I.framebufferRenderbuffer(a,b,c,$c[d])},wg:(a,b,c,d,e)=>{I.framebufferTexture2D(a,
b,c,ad[d],e)},Ud:(a,b,c,d,e)=>{I.framebufferTextureLayer(a,b,ad[c],d,e)},vg:a=>I.frontFace(a),ug:Re,sg:(a,b)=>{md(a,b,"createFramebuffer",Zc)},le:(a,b)=>{md(a,b,"createQuery",L)},Ih:(a,b)=>{for(var c=0;c<a;c++){var d=I.ti.createQueryEXT();if(!d){for(P||=1282;c<a;)u[b+4*c++>>2]=0;break}var e=ld(L);d.name=e;L[e]=d;u[b+4*c>>2]=e}},rg:(a,b)=>{md(a,b,"createRenderbuffer",$c)},Rc:(a,b)=>{md(a,b,"createSampler",cd)},qg:Se,Dc:(a,b)=>{md(a,b,"createTransformFeedback",dd)},Od:Te,vh:Te,tg:Ue,pg:(a,b,c,d,e,f,
g)=>Ve("getActiveAttrib",a,b,c,d,e,f,g),og:(a,b,c,d,e,f,g)=>Ve("getActiveUniform",a,b,c,d,e,f,g),cd:(a,b,c,d,e)=>{a=J[a];if(a=I.getActiveUniformBlockName(a,b))e&&0<c?(c=A(a,t,e,c),d&&(u[d>>2]=c)):d&&(u[d>>2]=0)},dd:(a,b,c,d)=>{if(d)if(a=J[a],35393==c)u[d>>2]=I.getActiveUniformBlockName(a,b).length+1;else{if(a=I.getActiveUniformBlockParameter(a,b,c),null!==a)if(35395==c)for(c=0;c<a.length;c++)u[d+4*c>>2]=a[c];else u[d>>2]=a}else P||=1281},fd:(a,b,c,d,e)=>{if(e)if(0<b&&0==c)P||=1281;else{a=J[a];for(var f=
[],g=0;g<b;g++)f.push(u[c+4*g>>2]);if(a=I.getActiveUniforms(a,f,d))for(b=a.length,g=0;g<b;g++)u[e+4*g>>2]=a[g]}else P||=1281},ng:(a,b,c,d)=>{a=I.getAttachedShaders(J[a]);var e=a.length;e>b&&(e=b);u[c>>2]=e;for(b=0;b<e;++b)u[d+4*b>>2]=K.indexOf(a[b])},mg:(a,b)=>I.getAttribLocation(J[a],b?z(t,b):""),lg:(a,b)=>Ye(a,b,4),Sc:(a,b,c)=>{c?We(c,I.getBufferParameter(a,b)):P||=1281},kg:(a,b,c)=>{c?u[c>>2]=I.getBufferParameter(a,b):P||=1281},de:(a,b,c)=>{if(35005==b){b=0;if(a=Yc[Pe(a)])b=a.Ji;u[c>>2]=b}else P||=
1280,l("GL_INVALID_ENUM in glGetBufferPointerv")},jg:()=>{var a=I.getError()||P;P=0;return a},ig:(a,b)=>Ye(a,b,2),xd:(a,b)=>I.getFragDataLocation(J[a],b?z(t,b):""),hg:(a,b,c,d)=>{a=I.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;u[d>>2]=a},Tc:(a,b,c)=>Ze(a,b,c,1),Vc:(a,b)=>{Ye(a,b,1)},Md:(a,b,c)=>Ze(a,b,c,0),gg:$e,rc:(a,b,c,d,e)=>{if(0>d)P||=1281;else if(e){if(a=I.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&b<d;++b)u[e+
4*b>>2]=a[b]}else P||=1281},zc:()=>{P||=1282},eg:af,fg:bf,zh:cf,Bh:df,yh:cf,fe:(a,b,c)=>{if(c){a=I.getQueryParameter(L[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else P||=1281},Ah:df,ge:(a,b,c)=>{c?u[c>>2]=I.getQuery(a,b):P||=1281},Ch:(a,b,c)=>{c?u[c>>2]=I.ti.getQueryEXT(a,b):P||=1281},dg:(a,b,c)=>{c?u[c>>2]=I.getRenderbufferParameter(a,b):P||=1281},Hc:(a,b,c)=>{c?x[c>>2]=I.getSamplerParameter(cd[a],b):P||=1281},Ic:(a,b,c)=>{c?u[c>>2]=I.getSamplerParameter(cd[a],b):P||=1281},bg:ef,ag:(a,
b,c,d)=>{a=I.getShaderPrecisionFormat(a,b);u[c>>2]=a.rangeMin;u[c+4>>2]=a.rangeMax;u[d>>2]=a.precision},$f:(a,b,c,d)=>{if(a=I.getShaderSource(K[a]))b=0<b&&d?A(a,t,d,b):0,c&&(u[c>>2]=b)},cg:ff,_f:gf,id:(a,b)=>{if(2>Q.version)return P||=1282,0;var c=hd[a];if(c)return 0>b||b>=c.length?(P||=1281,0):c[b];switch(a){case 7939:return c=Xe().map(sd),c=hd[a]=c,0>b||b>=c.length?(P||=1281,0):c[b];default:return P||=1280,0}},Uc:(a,b,c,d,e)=>{0>c?P||=1281:e?(a=I.getSyncParameter(ed[a],b),null!==a&&(u[e>>2]=a,d&&
(u[d>>2]=1))):P||=1281},Zf:(a,b,c)=>{c?x[c>>2]=I.getTexParameter(a,b):P||=1281},Yf:(a,b,c)=>{c?u[c>>2]=I.getTexParameter(a,b):P||=1281},Gd:(a,b,c,d,e,f,g)=>{a=J[a];if(a=I.getTransformFeedbackVarying(a,b))g&&0<c?(c=A(a.name,t,g,c),d&&(u[d>>2]=c)):d&&(u[d>>2]=0),e&&(u[e>>2]=a.size),f&&(u[f>>2]=a.type)},ed:(a,b)=>I.getUniformBlockIndex(J[a],b?z(t,b):""),gd:(a,b,c,d)=>{if(d)if(0<b&&(0==c||0==d))P||=1281;else{a=J[a];for(var e=[],f=0;f<b;f++)e.push(pc(w[c+4*f>>2]));if(a=I.getUniformIndices(a,e))for(b=a.length,
f=0;f<b;f++)u[d+4*f>>2]=a[f]}else P||=1281},Vf:kf,Xf:(a,b,c)=>{lf(a,b,c,2)},Wf:(a,b,c)=>{lf(a,b,c,0)},yd:(a,b,c)=>lf(a,b,c,0),Ed:nf,Dd:nf,Sf:(a,b,c)=>{c?(Q.Bi[a].enabled&&l("glGetVertexAttribPointer on client-side array: not supported, bad data returned"),u[c>>2]=I.getVertexAttribOffset(a,b)):P||=1281},Uf:(a,b,c)=>{mf(a,b,c,2)},Tf:(a,b,c)=>{mf(a,b,c,5)},Rf:(a,b)=>I.hint(a,b),wc:(a,b,c)=>{for(var d=Je[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];I.invalidateFramebuffer(a,d)},uc:(a,b,c,d,e,f,g)=>{for(var k=Je[b],
m=0;m<b;m++)k[m]=u[c+4*m>>2];I.invalidateSubFramebuffer(a,k,d,e,f,g)},Qf:a=>(a=Xc[a])?I.isBuffer(a):0,Pf:a=>I.isEnabled(a),Of:a=>(a=Zc[a])?I.isFramebuffer(a):0,Nf:a=>(a=J[a])?I.isProgram(a):0,je:a=>(a=L[a])?I.isQuery(a):0,Gh:a=>(a=L[a])?I.ti.isQueryEXT(a):0,Mf:a=>(a=$c[a])?I.isRenderbuffer(a):0,Oc:a=>(a=cd[a])?I.isSampler(a):0,Lf:a=>(a=K[a])?I.isShader(a):0,Zc:a=>I.isSync(ed[a]),Kf:a=>(a=ad[a])?I.isTexture(a):0,Cc:a=>I.isTransformFeedback(dd[a]),Nd:of,uh:of,Jf:pf,If:qf,Td:(a,b,c,d)=>{if(0!=(d&33))return l("glMapBufferRange access does not support MAP_READ or MAP_UNSYNCHRONIZED"),
0;if(0==(d&2))return l("glMapBufferRange access must include MAP_WRITE"),0;if(0==(d&12))return l("glMapBufferRange access must include INVALIDATE_BUFFER or INVALIDATE_RANGE"),0;if(!Qe(a))return P||=1280,l("GL_INVALID_ENUM in glMapBufferRange"),0;var e=rd(c);a=Pe(a);if(!e)return 0;let f;a=Yc[f=a]??(Yc[f]={});a.offset=b;a.length=c;a.Ji=e;a.Bj=d;return e},Bc:()=>I.pauseTransformFeedback(),Hf:rf,Ce:(a,b)=>{I.uk.polygonModeWEBGL(a,b)},Gf:(a,b)=>I.polygonOffset(a,b),Fe:(a,b,c)=>{I.ek.polygonOffsetClampEXT(a,
b,c)},yc:()=>{P||=1280},xc:()=>{P||=1280},Dh:(a,b)=>{I.ti.queryCounterEXT(L[a],b)},se:a=>I.readBuffer(a),Ff:tf,Df:()=>{},Cf:(a,b,c,d)=>I.renderbufferStorage(a,b,c,d),Vd:(a,b,c,d,e)=>I.renderbufferStorageMultisample(a,b,c,d,e),Ac:()=>I.resumeTransformFeedback(),Bf:(a,b)=>{I.sampleCoverage(a,!!b)},Kc:(a,b,c)=>{I.samplerParameterf(cd[a],b,c)},Jc:(a,b,c)=>{I.samplerParameterf(cd[a],b,x[c>>2])},Mc:(a,b,c)=>{I.samplerParameteri(cd[a],b,c)},Lc:(a,b,c)=>{I.samplerParameteri(cd[a],b,u[c>>2])},Af:(a,b,c,d)=>
I.scissor(a,b,c,d),zf:()=>{P||=1280},yf:uf,xf:(a,b,c)=>I.stencilFunc(a,b,c),wf:(a,b,c,d)=>I.stencilFuncSeparate(a,b,c,d),vf:a=>I.stencilMask(a),uf:(a,b)=>I.stencilMaskSeparate(a,b),sf:(a,b,c)=>I.stencilOp(a,b,c),rf:(a,b,c,d)=>I.stencilOpSeparate(a,b,c,d),qf:wf,qe:(a,b,c,d,e,f,g,k,m,n)=>{if(I.xi)I.texImage3D(a,b,c,d,e,f,g,k,m,n);else if(n){var q=sf(m);I.texImage3D(a,b,c,d,e,f,g,k,m,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else I.texImage3D(a,b,c,d,e,f,g,k,m,null)},pf:(a,b,c)=>I.texParameterf(a,b,
c),of:(a,b,c)=>{I.texParameterf(a,b,x[c>>2])},nf:xf,mf:(a,b,c)=>{I.texParameteri(a,b,u[c>>2])},tc:(a,b,c,d,e)=>I.texStorage2D(a,b,c,d,e),sc:(a,b,c,d,e,f)=>I.texStorage3D(a,b,c,d,e,f),lf:(a,b,c,d,e,f,g,k,m)=>{if(I.xi)I.texSubImage2D(a,b,c,d,e,f,g,k,m);else if(m){var n=sf(k);I.texSubImage2D(a,b,c,d,e,f,g,k,n,m>>>31-Math.clz32(n.BYTES_PER_ELEMENT))}else m=m?vf(k,g,e,f,m):null,I.texSubImage2D(a,b,c,d,e,f,g,k,m)},pe:(a,b,c,d,e,f,g,k,m,n,q)=>{if(I.xi)I.texSubImage3D(a,b,c,d,e,f,g,k,m,n,q);else if(q){var r=
sf(n);I.texSubImage3D(a,b,c,d,e,f,g,k,m,n,r,q>>>31-Math.clz32(r.BYTES_PER_ELEMENT))}else I.texSubImage3D(a,b,c,d,e,f,g,k,m,n,null)},Hd:(a,b,c,d)=>{a=J[a];for(var e=[],f=0;f<b;f++)e.push(pc(w[c+4*f>>2]));I.transformFeedbackVaryings(a,e,d)},kf:yf,jf:zf,hf:Af,gf:Bf,wd:(a,b)=>{I.uniform1ui(Y(a),b)},rd:(a,b,c)=>{b&&I.uniform1uiv(Y(a),w,c>>2,b)},ff:(a,b,c)=>{I.uniform2f(Y(a),b,c)},ef:Cf,df:(a,b,c)=>{I.uniform2i(Y(a),b,c)},cf:(a,b,c)=>{b&&I.uniform2iv(Y(a),u,c>>2,2*b)},vd:(a,b,c)=>{I.uniform2ui(Y(a),b,c)},
qd:(a,b,c)=>{b&&I.uniform2uiv(Y(a),w,c>>2,2*b)},bf:(a,b,c,d)=>{I.uniform3f(Y(a),b,c,d)},af:Df,$e:(a,b,c,d)=>{I.uniform3i(Y(a),b,c,d)},_e:(a,b,c)=>{b&&I.uniform3iv(Y(a),u,c>>2,3*b)},td:(a,b,c,d)=>{I.uniform3ui(Y(a),b,c,d)},pd:(a,b,c)=>{b&&I.uniform3uiv(Y(a),w,c>>2,3*b)},Ze:(a,b,c,d,e)=>{I.uniform4f(Y(a),b,c,d,e)},Ye:Ef,Xe:(a,b,c,d,e)=>{I.uniform4i(Y(a),b,c,d,e)},We:(a,b,c)=>{b&&I.uniform4iv(Y(a),u,c>>2,4*b)},sd:(a,b,c,d,e)=>{I.uniform4ui(Y(a),b,c,d,e)},od:(a,b,c)=>{b&&I.uniform4uiv(Y(a),w,c>>2,4*b)},
bd:(a,b,c)=>{a=J[a];I.uniformBlockBinding(a,b,c)},Ve:(a,b,c,d)=>{b&&I.uniformMatrix2fv(Y(a),!!c,x,d>>2,4*b)},be:(a,b,c,d)=>{b&&I.uniformMatrix2x3fv(Y(a),!!c,x,d>>2,6*b)},$d:(a,b,c,d)=>{b&&I.uniformMatrix2x4fv(Y(a),!!c,x,d>>2,8*b)},Ue:Ff,ae:(a,b,c,d)=>{b&&I.uniformMatrix3x2fv(Y(a),!!c,x,d>>2,6*b)},Yd:(a,b,c,d)=>{b&&I.uniformMatrix3x4fv(Y(a),!!c,x,d>>2,12*b)},Te:Gf,Zd:(a,b,c,d)=>{b&&I.uniformMatrix4x2fv(Y(a),!!c,x,d>>2,8*b)},Xd:(a,b,c,d)=>{b&&I.uniformMatrix4x3fv(Y(a),!!c,x,d>>2,12*b)},ee:a=>{if(!Qe(a))return P||=
1280,l("GL_INVALID_ENUM in glUnmapBuffer"),0;var b=Yc[Pe(a)];if(!b||!b.Ji)return P||=1282,l("buffer was never mapped in glUnmapBuffer"),0;b.Bj&16||I.bufferSubData(a,b.offset,t,b.Ji,b.length);fg(b.Ji);b.Ji=0;return 1},Se:Hf,Re:a=>{I.validateProgram(J[a])},Qe:(a,b)=>I.vertexAttrib1f(a,b),Oe:(a,b)=>{I.vertexAttrib1f(a,x[b>>2])},Ne:(a,b,c)=>I.vertexAttrib2f(a,b,c),Me:(a,b)=>{I.vertexAttrib2f(a,x[b>>2],x[b+4>>2])},Le:(a,b,c,d)=>I.vertexAttrib3f(a,b,c,d),Ke:(a,b)=>{I.vertexAttrib3f(a,x[b>>2],x[b+4>>2],
x[b+8>>2])},Je:(a,b,c,d,e)=>I.vertexAttrib4f(a,b,c,d,e),Ie:(a,b)=>{I.vertexAttrib4f(a,x[b>>2],x[b+4>>2],x[b+8>>2],x[b+12>>2])},Gc:If,qh:If,Ae:If,Be:If,qc:If,Cd:(a,b,c,d,e)=>I.vertexAttribI4i(a,b,c,d,e),Ad:(a,b)=>{I.vertexAttribI4i(a,u[b>>2],u[b+4>>2],u[b+8>>2],u[b+12>>2])},Bd:(a,b,c,d,e)=>I.vertexAttribI4ui(a,b,c,d,e),zd:(a,b)=>{I.vertexAttribI4ui(a,w[b>>2],w[b+4>>2],w[b+8>>2],w[b+12>>2])},Fd:(a,b,c,d,e)=>{var f=Q.Bi[a];I.Ni?(f.Mi=!1,I.vertexAttribIPointer(a,b,c,d,e)):(f.size=b,f.type=c,f.rj=!1,f.stride=
d,f.ii=e,f.Mi=!0,f.yj=function(g,k,m,n,q,r){this.vertexAttribIPointer(g,k,m,q,r)})},He:Jf,Ge:Kf,Wc:(a,b,c)=>{c=Number(c);I.waitSync(ed[a],b,c)},$:()=>0,Kh:(a,b,c)=>Lf(a,{Ri:u[c>>2],Li:u[c+4>>2],Hj:u[c+8>>2],ak:b,si:u[c+12>>2],Ki:u[c+16>>2]}),ma:(a,b)=>{a=U(a);return a?a.requestPointerLock?Td()?le(a):b?(Rd(le,2,[a]),1):-2:-1:-4},Sb:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,
d)/65536))-xa.buffer.byteLength+65535)/65536|0;try{xa.grow(d);wa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},Ia:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:Mf(a,b),Ua:(a,b,c,d)=>Nf(a,b,c,d,12,"blur"),N:ee,Z:(a,b,c)=>{a=U(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},Va:(a,b,c,d)=>Nf(a,b,c,d,13,"focus"),La:(a,b,c,d)=>{if(!S.fullscreenEnabled())return-1;a=U(a);if(!a)return-4;Of(a,b,c,d,"webkitfullscreenchange");return Of(a,b,c,d,"fullscreenchange")},
pb:(a,b,c)=>Qf()?-1:Pf(a,b,c,26,"gamepadconnected"),ob:(a,b,c)=>Qf()?-1:Pf(a,b,c,27,"gamepaddisconnected"),Oa:(a,b,c,d)=>Rf(a,b,c,d,2,"keydown"),Ma:(a,b,c,d)=>Rf(a,b,c,d,1,"keypress"),Na:(a,b,c,d)=>Rf(a,b,c,d,3,"keyup"),jd:(a,b,c)=>{a=y(a);Jd(a,b,c)},ka:(a,b,c,d)=>Tf(a,b,c,d,5,"mousedown"),ia:(a,b,c,d)=>Tf(a,b,c,d,33,"mouseenter"),ha:(a,b,c,d)=>Tf(a,b,c,d,34,"mouseleave"),la:(a,b,c,d)=>Tf(a,b,c,d,8,"mousemove"),ja:(a,b,c,d)=>Tf(a,b,c,d,6,"mouseup"),Pa:(a,b,c,d)=>document.body?.requestPointerLock?
(a=U(a))?Uf(a,b,c,d):-4:-1,Ka:(a,b,c,d)=>Vf(a,b,c,d),Qa:(a,b,c,d)=>Wf(a,b,c,d,25,"touchcancel"),Sa:(a,b,c,d)=>Wf(a,b,c,d,23,"touchend"),Ra:(a,b,c,d)=>Wf(a,b,c,d,24,"touchmove"),Ta:(a,b,c,d)=>Wf(a,b,c,d,22,"touchstart"),Ja:(a,b,c)=>ae[1]?Xf(a,b,c):-4,Wa:(a,b,c,d)=>(a=U(a))?"undefined"!=typeof a.onwheel?Yf(a,b,c,d):-1:-4,Lh:a=>document.title=a?z(t,a):"",_:()=>{ya("Please compile your program with async support in order to use asynchronous operations like emscripten_sleep")},ac:(a,b)=>{var c=0,d=0,e;
for(e of ag()){var f=b+c;w[a+d>>2]=f;c+=A(e,t,f,Infinity)+1;d+=4}return 0},bc:(a,b)=>{var c=ag();w[a>>2]=c.length;a=0;for(var d of c)a+=bb(d)+1;w[b>>2]=a;return 0},tf:a=>{oa=a;Ac(a)},X:function(a){try{var b=Rb(a);fc(b);return 0}catch(c){if("undefined"==typeof F||"ErrnoError"!==c.name)throw c;return c.hi}},xa:function(a,b,c,d){try{a:{var e=Rb(a);a=b;for(var f,g=b=0;g<c;g++){var k=w[a>>2],m=w[a+4>>2];a+=8;var n=e,q=k,r=m,v=f,D=p;if(0>r||0>v)throw new B(28);if(null===n.fd)throw new B(8);if(1===(n.flags&
2097155))throw new B(8);if(E(n.node.mode))throw new B(31);if(!n.fi.read)throw new B(28);var N="undefined"!=typeof v;if(!N)v=n.position;else if(!n.seekable)throw new B(70);var O=n.fi.read(n,D,q,r,v);N||(n.position+=O);var R=O;if(0>R){var M=-1;break a}b+=R;if(R<m)break;"undefined"!=typeof f&&(f+=R)}M=b}w[d>>2]=M;return 0}catch(T){if("undefined"==typeof F||"ErrnoError"!==T.name)throw T;return T.hi}},$b:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;
var e=Rb(a);gc(e,b,c);ua[d>>3]=BigInt(e.position);e.Ii&&0===b&&0===c&&(e.Ii=null);return 0}catch(f){if("undefined"==typeof F||"ErrnoError"!==f.name)throw f;return f.hi}},ic:function(a,b,c,d){try{a:{var e=Rb(a);a=b;for(var f,g=b=0;g<c;g++){var k=w[a>>2],m=w[a+4>>2];a+=8;var n=hc(e,p,k,m,f);if(0>n){var q=-1;break a}b+=n;if(n<m)break;"undefined"!=typeof f&&(f+=n)}q=b}w[d>>2]=q;return 0}catch(r){if("undefined"==typeof F||"ErrnoError"!==r.name)throw r;return r.hi}},sb:ne,Qc:oe,B:pe,C:qe,E:re,q:se,fa:te,
Ha:ue,te:ve,Ee:we,Wb:xe,Ef:ye,Jb:ze,kc:Ae,z:Be,Lb:Ce,Ba:De,Q:Ee,A:Fe,ud:Ge,Ga:He,tb:Le,p:Ne,J:Oe,S:Re,wb:Se,aa:Te,ub:Ue,ea:$e,Cb:af,ta:bf,vc:ef,Aa:ff,Pe:gf,Bb:kf,Y:pf,Hb:qf,Ca:rf,Da:tf,ec:uf,vb:wf,T:xf,Ab:yf,xb:zf,U:Af,yb:Bf,qa:Cf,pa:Df,oa:Ef,zb:Ff,H:Gf,G:Hf,I:Jf,Ea:Kf,F:lg,b:mg,g:ng,d:og,s:pg,r:qg,u:rg,ra:sg,sa:tg,W:ug,Eb:vg,Fb:wg,Gb:xg,va:yg,Db:zg,ba:Ag,R:Bg,i:Cg,j:Dg,t:Eg,L:Fg,f:Gg,c:Hg,h:Ig,wa:Jg,o:Kg,M:Lg,x:Mg,K:Ng,V:Og,ua:Pg,y:a=>a,Mb:Ac};
function mg(a,b){var c=V();try{return y(a)(b)}catch(d){X(c);if(d!==d+0)throw d;Z(1,0)}}function Gg(a,b,c){var d=V();try{y(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Z(1,0)}}function ng(a,b,c){var d=V();try{return y(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Z(1,0)}}function rg(a,b,c,d,e,f,g){var k=V();try{return y(a)(b,c,d,e,f,g)}catch(m){X(k);if(m!==m+0)throw m;Z(1,0)}}function Dg(a,b){var c=V();try{y(a)(b)}catch(d){X(c);if(d!==d+0)throw d;Z(1,0)}}
function Cg(a){var b=V();try{y(a)()}catch(c){X(b);if(c!==c+0)throw c;Z(1,0)}}function og(a,b,c,d){var e=V();try{return y(a)(b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Z(1,0)}}function Hg(a,b,c,d){var e=V();try{y(a)(b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Z(1,0)}}function Ig(a,b,c,d,e){var f=V();try{y(a)(b,c,d,e)}catch(g){X(f);if(g!==g+0)throw g;Z(1,0)}}function Lg(a,b,c,d,e,f,g){var k=V();try{y(a)(b,c,d,e,f,g)}catch(m){X(k);if(m!==m+0)throw m;Z(1,0)}}
function Eg(a,b,c){var d=V();try{y(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Z(1,0)}}function Kg(a,b,c,d,e,f){var g=V();try{y(a)(b,c,d,e,f)}catch(k){X(g);if(k!==k+0)throw k;Z(1,0)}}function Jg(a,b,c,d,e,f){var g=V();try{y(a)(b,c,d,e,f)}catch(k){X(g);if(k!==k+0)throw k;Z(1,0)}}function yg(a,b,c,d,e){var f=V();try{return y(a)(b,c,d,e)}catch(g){X(f);if(g!==g+0)throw g;Z(1,0)}}function lg(a,b,c){var d=V();try{return y(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Z(1,0)}}
function Pg(a,b,c,d){var e=V();try{y(a)(b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Z(1,0)}}function Fg(a,b,c,d,e){var f=V();try{y(a)(b,c,d,e)}catch(g){X(f);if(g!==g+0)throw g;Z(1,0)}}function Mg(a,b,c,d,e,f,g,k){var m=V();try{y(a)(b,c,d,e,f,g,k)}catch(n){X(m);if(n!==n+0)throw n;Z(1,0)}}function pg(a,b,c,d,e){var f=V();try{return y(a)(b,c,d,e)}catch(g){X(f);if(g!==g+0)throw g;Z(1,0)}}function Ag(a,b){var c=V();try{return y(a)(b)}catch(d){X(c);if(d!==d+0)throw d;Z(1,0);return 0n}}
function qg(a,b,c,d,e,f){var g=V();try{return y(a)(b,c,d,e,f)}catch(k){X(g);if(k!==k+0)throw k;Z(1,0)}}function Bg(a,b,c,d){var e=V();try{return y(a)(b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Z(1,0);return 0n}}function tg(a,b,c,d,e,f,g,k,m,n){var q=V();try{return y(a)(b,c,d,e,f,g,k,m,n)}catch(r){X(q);if(r!==r+0)throw r;Z(1,0)}}function xg(a,b,c,d){var e=V();try{return y(a)(b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Z(1,0)}}
function wg(a,b,c,d,e){var f=V();try{return y(a)(b,c,d,e)}catch(g){X(f);if(g!==g+0)throw g;Z(1,0)}}function vg(a,b,c,d,e,f){var g=V();try{return y(a)(b,c,d,e,f)}catch(k){X(g);if(k!==k+0)throw k;Z(1,0)}}function zg(a,b,c){var d=V();try{return y(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Z(1,0)}}function sg(a,b,c,d,e,f,g,k){var m=V();try{return y(a)(b,c,d,e,f,g,k)}catch(n){X(m);if(n!==n+0)throw n;Z(1,0)}}
function ug(a,b,c,d,e,f,g,k,m,n,q,r){var v=V();try{return y(a)(b,c,d,e,f,g,k,m,n,q,r)}catch(D){X(v);if(D!==D+0)throw D;Z(1,0)}}function Ng(a,b,c,d,e,f,g,k,m,n,q){var r=V();try{y(a)(b,c,d,e,f,g,k,m,n,q)}catch(v){X(r);if(v!==v+0)throw v;Z(1,0)}}function Og(a,b,c,d,e,f,g,k,m,n,q,r,v,D,N,O){var R=V();try{y(a)(b,c,d,e,f,g,k,m,n,q,r,v,D,N,O)}catch(M){X(R);if(M!==M+0)throw M;Z(1,0)}}
function Rg(a=[]){var b=eg;a.unshift(ea);var c=a.length,d=be(4*(c+1)),e=d,f;for(f of a)w[e>>2]=ce(f),e+=4;w[e>>2]=0;try{var g=b(c,d);oa=g;Ac(g)}catch(k){zc(k)}}
function Sg(a=da){function b(){h.calledRun=!0;if(!na){va=!0;if(!h.noFSInit&&!Eb){var c,d;Eb=!0;c??=h.stdin;d??=h.stdout;e??=h.stderr;c?mc("/dev","stdin",c):$b("/dev/tty","/dev/stdin");d?mc("/dev","stdout",null,d):$b("/dev/tty","/dev/stdout");e?mc("/dev","stderr",null,e):$b("/dev/tty1","/dev/stderr");ec("/dev/stdin",0);ec("/dev/stdout",1);ec("/dev/stderr",1)}Tg.Nh();Fb=!1;pa?.(h);h.onRuntimeInitialized?.();h.noInitialRun||Rg(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var e=
h.postRun.shift();Fa.push(e)}Ea(Fa)}}if(0<rb)sb=Sg;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ha();Ea(Ga);0<rb?sb=Sg:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}var Tg;
Tg=await (async function(){function a(c){c=Tg=c.exports;h._gource_reset=c.Oh;h._gource_load_log=c.Ph;eg=h._main=c.Qh;rd=c.Sh;fg=c.Th;gg=c.Uh;jb=c.Vh;hg=c.Wh;Z=c.Xh;Pa=c.Yh;X=c.Zh;be=c._h;V=c.$h;ig=c.ai;jg=c.bi;Qa=c.ci;kg=c.di;xa=c.Mh;Ka=c.Rh;wa();return Tg}var b={a:Qg};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});za??=h.locateFile?h.locateFile("gource-web.wasm",ha):ha+"gource-web.wasm";return a((await Ca(b)).instance)}());Sg();
va?moduleRtn=h:moduleRtn=new Promise((a,b)=>{pa=a;qa=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=GourceModule;module.exports.default=GourceModule}else if(typeof define==="function"&&define["amd"])define([],()=>GourceModule);
